/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.pseudocell.gui.tests;

import org.pseudocell.gui.nodes.*;
import java.awt.Color;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.JOptionPane;
import org.pseudocell.core.nodes.Node;
import org.pseudocell.core.nodes.NodeModification;
import org.pseudocell.config.Config;

/**
 *
 * @author ViníciusPierdoná
 */
public class ModelCreateModification extends javax.swing.JFrame {

    private static final int TYPE_PROTEINGENE = 1;
    private static final int TYPE_METABOLITE = 2;
    private static final int TYPE_OTHER = 3;
    private static final int TYPE_MIRNA = 4;
    private static final int TYPE_DRUG = 5;

    Config configurations;
    Node node;
    boolean nodeListModification;

    Color colorBlock;
    Color colorEnabled;

    /**
     * Creates new form ModificationAdd
     *
     * @param configurations
     * @param node
     */
    public ModelCreateModification(Config configurations, Node node) {
        initComponents();

        this.configurations = configurations;
        this.node = node;
        this.nodeListModification = false;

        colorBlock = new Color(53, 55, 71);
        colorEnabled = new Color(69, 71, 95);

        // Create a listener to control the methods needed when shown or hidden the card
        addComponentListener(new ComponentAdapter() {
            @Override
            public void componentHidden(ComponentEvent evt) {
                hidden();
            }

            @Override
            public void componentShown(ComponentEvent evt) {
                shown();
            }
        });
    }

    public void hidden() {
        if (nodeListModification) {
            // If any nodes have been created, ensures that the network used in the execution contains the changes made by the user.
            configurations.networkSourceInputType = "xml";
        }
    }

    public void shown() {
        setComponents();
    }

    public void setComponents() {
        jTextFieldNodeName.setText(node.getName());
        switch (node.getType()) {
            case TYPE_PROTEINGENE:
                jTextFieldNodeType.setText("Protein/Gene");
                break;
            case TYPE_METABOLITE:
                jTextFieldNodeType.setText("Metabolite");
                break;
            case TYPE_OTHER:
                jTextFieldNodeType.setText("Other");
                break;
            case TYPE_MIRNA:
                jTextFieldNodeType.setText("miRNA");
                ;
                break;
            case TYPE_DRUG:
                jTextFieldNodeType.setText("Drug");
                break;
            default:
                throw new AssertionError();
        }
        jTextFieldNodeName.setEditable(false);
        jTextFieldNodeType.setEditable(false);
        jTextFieldNodeName.setBackground(colorBlock);
        jTextFieldNodeType.setBackground(colorBlock);
        if (!node.getNodeModifications().isEmpty()) {
            for (int i = 0; i < node.getNodeModifications().size(); i++) {
                NodeModification modification = node.getNodeModifications().get(i);
                listMod.add("[Mod] " + modification.getName() + " - Resting Status: " + modification.getRestingStatus());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelModificationAddScreen = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabelSubtitle = new javax.swing.JLabel();
        jLabelNodeName = new javax.swing.JLabel();
        jTextFieldNodeName = new javax.swing.JTextField();
        jLabelNodeType = new javax.swing.JLabel();
        jTextFieldNodeType = new javax.swing.JTextField();
        jButtonCancel = new javax.swing.JButton();
        jButtonCreate = new javax.swing.JButton();
        jLabelTitle = new javax.swing.JLabel();
        jLabelModName = new javax.swing.JLabel();
        jTextFieldModName = new javax.swing.JTextField();
        jLabelModStatus = new javax.swing.JLabel();
        jTextFieldModStatus = new javax.swing.JTextField();
        jLabelModList = new javax.swing.JLabel();
        jLabelModRestingStatus = new javax.swing.JLabel();
        jTextFieldRestingStatus = new javax.swing.JTextField();
        listMod = new java.awt.List();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanelModificationAddScreen.setBackground(new java.awt.Color(56, 58, 77));
        jPanelModificationAddScreen.setMaximumSize(new java.awt.Dimension(680, 480));
        jPanelModificationAddScreen.setPreferredSize(new java.awt.Dimension(680, 480));

        jLabelSubtitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelSubtitle.setForeground(new java.awt.Color(204, 204, 255));
        jLabelSubtitle.setText("Create a new modification");

        jLabelNodeName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNodeName.setForeground(new java.awt.Color(204, 204, 255));
        jLabelNodeName.setText("Node name");

        jTextFieldNodeName.setBackground(new java.awt.Color(69, 71, 95));
        jTextFieldNodeName.setForeground(new java.awt.Color(255, 255, 255));

        jLabelNodeType.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNodeType.setForeground(new java.awt.Color(204, 204, 255));
        jLabelNodeType.setText("Node type");

        jTextFieldNodeType.setBackground(new java.awt.Color(69, 71, 95));
        jTextFieldNodeType.setForeground(new java.awt.Color(255, 255, 255));

        jButtonCancel.setBackground(new java.awt.Color(126, 129, 161));
        jButtonCancel.setForeground(new java.awt.Color(51, 51, 51));
        jButtonCancel.setText("Cancel");
        jButtonCancel.setBorderPainted(false);
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonCreate.setBackground(new java.awt.Color(126, 129, 161));
        jButtonCreate.setForeground(new java.awt.Color(51, 51, 51));
        jButtonCreate.setText("Create");
        jButtonCreate.setBorderPainted(false);
        jButtonCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateActionPerformed(evt);
            }
        });

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(204, 204, 255));
        jLabelTitle.setText("Edit Network");

        jLabelModName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelModName.setForeground(new java.awt.Color(204, 204, 255));
        jLabelModName.setText("Modification name");

        jTextFieldModName.setBackground(new java.awt.Color(69, 71, 95));
        jTextFieldModName.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldModName.setText("newModification");

        jLabelModStatus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelModStatus.setForeground(new java.awt.Color(204, 204, 255));
        jLabelModStatus.setText("Modification initial status");

        jTextFieldModStatus.setBackground(new java.awt.Color(69, 71, 95));
        jTextFieldModStatus.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldModStatus.setText("0.0");

        jLabelModList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelModList.setForeground(new java.awt.Color(204, 204, 255));
        jLabelModList.setText("Modifications list");

        jLabelModRestingStatus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelModRestingStatus.setForeground(new java.awt.Color(204, 204, 255));
        jLabelModRestingStatus.setText("Modification resting status");

        jTextFieldRestingStatus.setBackground(new java.awt.Color(69, 71, 95));
        jTextFieldRestingStatus.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldRestingStatus.setText("0.0");

        listMod.setBackground(new java.awt.Color(69, 71, 95));
        listMod.setForeground(new java.awt.Color(255, 255, 255));
        listMod.setName(""); // NOI18N

        javax.swing.GroupLayout jPanelModificationAddScreenLayout = new javax.swing.GroupLayout(jPanelModificationAddScreen);
        jPanelModificationAddScreen.setLayout(jPanelModificationAddScreenLayout);
        jPanelModificationAddScreenLayout.setHorizontalGroup(
            jPanelModificationAddScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModificationAddScreenLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanelModificationAddScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelModificationAddScreenLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanelModificationAddScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelModificationAddScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelModificationAddScreenLayout.createSequentialGroup()
                                    .addComponent(jLabelSubtitle)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabelTitle))
                            .addGroup(jPanelModificationAddScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelNodeType)
                                .addComponent(jTextFieldNodeType, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelModList)
                                .addComponent(listMod, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelModificationAddScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanelModificationAddScreenLayout.createSequentialGroup()
                            .addComponent(jButtonCreate)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButtonCancel))
                        .addGroup(jPanelModificationAddScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNodeName)
                            .addComponent(jTextFieldNodeName, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelModName)
                            .addComponent(jTextFieldModName, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelModStatus)
                            .addComponent(jTextFieldModStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelModRestingStatus)
                            .addComponent(jTextFieldRestingStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanelModificationAddScreenLayout.setVerticalGroup(
            jPanelModificationAddScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModificationAddScreenLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelModificationAddScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelSubtitle)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelModificationAddScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelModificationAddScreenLayout.createSequentialGroup()
                        .addGroup(jPanelModificationAddScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNodeName)
                            .addComponent(jLabelNodeType))
                        .addGap(0, 0, 0)
                        .addComponent(jTextFieldNodeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelModificationAddScreenLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jTextFieldNodeType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(jPanelModificationAddScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelModificationAddScreenLayout.createSequentialGroup()
                        .addComponent(jLabelModName)
                        .addGap(0, 0, 0)
                        .addComponent(jTextFieldModName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelModStatus)
                        .addGap(0, 0, 0)
                        .addComponent(jTextFieldModStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelModRestingStatus)
                        .addGap(0, 0, 0)
                        .addComponent(jTextFieldRestingStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelModificationAddScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonCreate)
                            .addComponent(jButtonCancel)))
                    .addGroup(jPanelModificationAddScreenLayout.createSequentialGroup()
                        .addComponent(jLabelModList)
                        .addGap(0, 0, 0)
                        .addComponent(listMod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(298, 298, 298))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelModificationAddScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelModificationAddScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateActionPerformed
        int dialogResult = JOptionPane.showConfirmDialog(null, "This action will create a modification within the selected node. Would you like to proceed?", "Warning", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
            if (jTextFieldModName.getText().isBlank() | jTextFieldModStatus.getText().isBlank() | jTextFieldRestingStatus.getText().isBlank()) {
                JOptionPane.showMessageDialog(this, "[ERROR] All fields must be filled.", "Error - Empty Field", JOptionPane.ERROR_MESSAGE);
                return;
            }
            String modificationName = jTextFieldModName.getText();
            Double modificationStatus = Double.valueOf(jTextFieldModStatus.getText());
            Double modificationResting = Double.valueOf(jTextFieldRestingStatus.getText());
            NodeModification modification = new NodeModification(modificationName, modificationStatus, modificationResting);
            node.getNodeModifications().add(modification);
            nodeListModification = true;
            JOptionPane.showMessageDialog(rootPane, "Modification created successfully.", "Modification created", JOptionPane.INFORMATION_MESSAGE);            
            listMod.removeAll();
            setComponents();
            
        }
    }//GEN-LAST:event_jButtonCreateActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonCreate;
    private javax.swing.JLabel jLabelModList;
    private javax.swing.JLabel jLabelModName;
    private javax.swing.JLabel jLabelModRestingStatus;
    private javax.swing.JLabel jLabelModStatus;
    private javax.swing.JLabel jLabelNodeName;
    private javax.swing.JLabel jLabelNodeType;
    private javax.swing.JLabel jLabelSubtitle;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanelModificationAddScreen;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField jTextFieldModName;
    private javax.swing.JTextField jTextFieldModStatus;
    private javax.swing.JTextField jTextFieldNodeName;
    private javax.swing.JTextField jTextFieldNodeType;
    private javax.swing.JTextField jTextFieldRestingStatus;
    private java.awt.List listMod;
    // End of variables declaration//GEN-END:variables
}
