/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.pseudocell.gui.tests;

import org.pseudocell.gui.nodes.*;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.pseudocell.core.nodes.Node;
import org.pseudocell.config.Config;
import org.pseudocell.gui.utils.NodeFilter;
import org.pseudocell.gui.utils.RuleSummary;

/**
 *
 * @author ViníciusPierdoná
 */
public class ModelCreateKnockout extends JFrame {

    private static final int TYPE_PROTEINGENE = 1;
    private static final int TYPE_METABOLITE = 2;
    private static final int TYPE_OTHER = 3;
    private static final int TYPE_MIRNA = 4;
    private static final int TYPE_DRUG = 5;

    Config configurations;
    List<Node> nodeList, displayedNodes;
    NodeFilter nodeFilter;
    Node selectedNode;
    RuleSummary ruleSummary;

    boolean nodeListModification;

    /**
     * Creates new form CreateKnockout
     *
     * @param configurations
     * @param nodeList
     */
    public ModelCreateKnockout(Config configurations, List<Node> nodeList) {
        initComponents();
        this.configurations = configurations;
        this.nodeList = nodeList;
        this.nodeFilter = new NodeFilter();
        this.ruleSummary = new RuleSummary();
        this.nodeListModification = false;

        // Create a listener to control the methods needed when shown or hidden the card
        addComponentListener(new ComponentAdapter() {
            @Override
            public void componentHidden(ComponentEvent evt) {
                hidden();
            }

            @Override
            public void componentShown(ComponentEvent evt) {
                shown();
            }
        });
    }

    public void hidden() {
        if (nodeListModification) {
            // If any nodes have been created, ensures that the network used in the execution contains the changes made by the user.
            configurations.networkSourceInputType = "xml";
        }
    }

    public void shown() {
        setComponents();
    }

    public void setComponents() {
        displayedNodes = nodeFilter.filterNodes(listNodeList, nodeList, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCreateKnockoutScreen = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabelSubtitle = new javax.swing.JLabel();
        jLabelNodeName = new javax.swing.JLabel();
        jTextFieldNodeName = new javax.swing.JTextField();
        jLabelNodeType = new javax.swing.JLabel();
        jTextFieldNodeType = new javax.swing.JTextField();
        jLabelTitle = new javax.swing.JLabel();
        jLabelStatus = new javax.swing.JLabel();
        jTextFieldStatus = new javax.swing.JTextField();
        jLabelNodeList = new javax.swing.JLabel();
        jLabelRestingStatus = new javax.swing.JLabel();
        jTextFieldRestingStatus = new javax.swing.JTextField();
        listNodeList = new java.awt.List();
        jTextFieldFilter = new javax.swing.JTextField();
        jLabelFilter = new javax.swing.JLabel();
        jButtonFilter = new javax.swing.JButton();
        jCheckBoxKnockdown = new javax.swing.JCheckBox();
        jLabelRules = new javax.swing.JLabel();
        listRules = new java.awt.List();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanelCreateKnockoutScreen.setBackground(new java.awt.Color(56, 58, 77));
        jPanelCreateKnockoutScreen.setMaximumSize(new java.awt.Dimension(680, 620));
        jPanelCreateKnockoutScreen.setPreferredSize(new java.awt.Dimension(680, 620));

        jLabelSubtitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelSubtitle.setForeground(new java.awt.Color(204, 204, 255));
        jLabelSubtitle.setText("Knockout a node");

        jLabelNodeName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNodeName.setForeground(new java.awt.Color(204, 204, 255));
        jLabelNodeName.setText("Node name");

        jTextFieldNodeName.setEditable(false);
        jTextFieldNodeName.setBackground(new java.awt.Color(53, 55, 71));
        jTextFieldNodeName.setForeground(new java.awt.Color(255, 255, 255));

        jLabelNodeType.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNodeType.setForeground(new java.awt.Color(204, 204, 255));
        jLabelNodeType.setText("Node type");

        jTextFieldNodeType.setEditable(false);
        jTextFieldNodeType.setBackground(new java.awt.Color(53, 55, 71));
        jTextFieldNodeType.setForeground(new java.awt.Color(255, 255, 255));

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(204, 204, 255));
        jLabelTitle.setText("Edit Network");

        jLabelStatus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelStatus.setForeground(new java.awt.Color(204, 204, 255));
        jLabelStatus.setText("Initial Status");

        jTextFieldStatus.setEditable(false);
        jTextFieldStatus.setBackground(new java.awt.Color(53, 55, 71));
        jTextFieldStatus.setForeground(new java.awt.Color(255, 255, 255));

        jLabelNodeList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNodeList.setForeground(new java.awt.Color(204, 204, 255));
        jLabelNodeList.setText("Node List");

        jLabelRestingStatus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelRestingStatus.setForeground(new java.awt.Color(204, 204, 255));
        jLabelRestingStatus.setText("Resting Status");

        jTextFieldRestingStatus.setEditable(false);
        jTextFieldRestingStatus.setBackground(new java.awt.Color(53, 55, 71));
        jTextFieldRestingStatus.setForeground(new java.awt.Color(255, 255, 255));

        listNodeList.setBackground(new java.awt.Color(69, 71, 95));
        listNodeList.setForeground(new java.awt.Color(255, 255, 255));
        listNodeList.setName(""); // NOI18N
        listNodeList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listNodeListMouseClicked(evt);
            }
        });

        jTextFieldFilter.setBackground(new java.awt.Color(69, 71, 95));
        jTextFieldFilter.setForeground(new java.awt.Color(255, 255, 255));

        jLabelFilter.setBackground(new java.awt.Color(204, 204, 255));
        jLabelFilter.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelFilter.setForeground(new java.awt.Color(204, 204, 255));
        jLabelFilter.setText("Filter");

        jButtonFilter.setBackground(new java.awt.Color(126, 129, 161));
        jButtonFilter.setForeground(new java.awt.Color(51, 51, 51));
        jButtonFilter.setText("Filter");
        jButtonFilter.setBorderPainted(false);
        jButtonFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFilterActionPerformed(evt);
            }
        });

        jCheckBoxKnockdown.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCheckBoxKnockdown.setForeground(new java.awt.Color(204, 204, 255));
        jCheckBoxKnockdown.setText("Knockdown");
        jCheckBoxKnockdown.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxKnockdownItemStateChanged(evt);
            }
        });

        jLabelRules.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelRules.setForeground(new java.awt.Color(204, 204, 255));
        jLabelRules.setText("Rules associated with this node");

        listRules.setBackground(new java.awt.Color(69, 71, 95));
        listRules.setForeground(new java.awt.Color(255, 255, 255));
        listRules.setName(""); // NOI18N

        javax.swing.GroupLayout jPanelCreateKnockoutScreenLayout = new javax.swing.GroupLayout(jPanelCreateKnockoutScreen);
        jPanelCreateKnockoutScreen.setLayout(jPanelCreateKnockoutScreenLayout);
        jPanelCreateKnockoutScreenLayout.setHorizontalGroup(
            jPanelCreateKnockoutScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCreateKnockoutScreenLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanelCreateKnockoutScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelCreateKnockoutScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabelTitle)
                        .addGroup(jPanelCreateKnockoutScreenLayout.createSequentialGroup()
                            .addComponent(jLabelSubtitle)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelCreateKnockoutScreenLayout.createSequentialGroup()
                            .addGroup(jPanelCreateKnockoutScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelCreateKnockoutScreenLayout.createSequentialGroup()
                                    .addComponent(jLabelNodeList)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(jPanelCreateKnockoutScreenLayout.createSequentialGroup()
                                    .addGroup(jPanelCreateKnockoutScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanelCreateKnockoutScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(listNodeList, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanelCreateKnockoutScreenLayout.createSequentialGroup()
                                                .addComponent(jLabelFilter)
                                                .addGap(258, 258, 258)))
                                        .addGroup(jPanelCreateKnockoutScreenLayout.createSequentialGroup()
                                            .addComponent(jTextFieldFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonFilter)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanelCreateKnockoutScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCheckBoxKnockdown, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCreateKnockoutScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNodeName)
                                    .addComponent(jTextFieldNodeName, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelStatus)
                                    .addComponent(jTextFieldStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelRestingStatus)
                                    .addComponent(jTextFieldRestingStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelNodeType)
                                    .addComponent(jTextFieldNodeType, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(jLabelRules)
                        .addComponent(listRules, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanelCreateKnockoutScreenLayout.setVerticalGroup(
            jPanelCreateKnockoutScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCreateKnockoutScreenLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCreateKnockoutScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelSubtitle)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelFilter)
                .addGap(0, 0, 0)
                .addGroup(jPanelCreateKnockoutScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxKnockdown)
                    .addComponent(jButtonFilter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCreateKnockoutScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNodeName)
                    .addComponent(jLabelNodeList))
                .addGroup(jPanelCreateKnockoutScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelCreateKnockoutScreenLayout.createSequentialGroup()
                        .addComponent(jTextFieldNodeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabelNodeType)
                        .addGap(0, 0, 0)
                        .addComponent(jTextFieldNodeType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabelStatus)
                        .addGap(0, 0, 0)
                        .addComponent(jTextFieldStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabelRestingStatus)
                        .addGap(0, 0, 0)
                        .addComponent(jTextFieldRestingStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(listNodeList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabelRules)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(listRules, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelCreateKnockoutScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanelCreateKnockoutScreen, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFilterActionPerformed
        listNodeList.removeAll();
        displayedNodes = nodeFilter.filterNodes(listNodeList, nodeList, jTextFieldFilter.getText());
    }//GEN-LAST:event_jButtonFilterActionPerformed

    private void listNodeListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listNodeListMouseClicked
        // Ensures the item will only be accessed on the second click
        if (evt.getClickCount() == 2) {
            int nodeIndex = listNodeList.getSelectedIndex();
            selectedNode = displayedNodes.get(nodeIndex);
            // Populates the fields with the selected node
            jTextFieldNodeName.setText(selectedNode.getName());
            jTextFieldStatus.setText(String.valueOf(selectedNode.getStatus()));
            jTextFieldRestingStatus.setText(String.valueOf(selectedNode.getRestingStatus()));
            // Set node type
            switch (selectedNode.getType()) {
                case TYPE_PROTEINGENE:
                    jTextFieldNodeType.setText("Protein/Gene");
                    break;
                case TYPE_METABOLITE:
                    jTextFieldNodeType.setText("Metabolite");
                    break;
                case TYPE_OTHER:
                    jTextFieldNodeType.setText("Other");
                    break;
                case TYPE_MIRNA:
                    jTextFieldNodeType.setText("miRNA");
                    ;
                    break;
                case TYPE_DRUG:
                    jTextFieldNodeType.setText("Drug");
                    break;
                default:
                    throw new AssertionError();
            }
            jCheckBoxKnockdown.setSelected(selectedNode.getKnockdown());
            listRules.removeAll();
            List<String> ruleList = ruleSummary.listRules(selectedNode);
            for (String ruleString : ruleList) {
                listRules.add(ruleString);
            }
        }
    }//GEN-LAST:event_listNodeListMouseClicked

    private void jCheckBoxKnockdownItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxKnockdownItemStateChanged
        if (jTextFieldNodeName.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "[ERROR] No nodes were selected.", "Error - Empty Node", JOptionPane.ERROR_MESSAGE);
            return;
        }
        selectedNode.setKnockdown(jCheckBoxKnockdown.isSelected());
        nodeListModification = true;        
    }//GEN-LAST:event_jCheckBoxKnockdownItemStateChanged
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFilter;
    private javax.swing.JCheckBox jCheckBoxKnockdown;
    private javax.swing.JLabel jLabelFilter;
    private javax.swing.JLabel jLabelNodeList;
    private javax.swing.JLabel jLabelNodeName;
    private javax.swing.JLabel jLabelNodeType;
    private javax.swing.JLabel jLabelRestingStatus;
    private javax.swing.JLabel jLabelRules;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelSubtitle;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanelCreateKnockoutScreen;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField jTextFieldFilter;
    private javax.swing.JTextField jTextFieldNodeName;
    private javax.swing.JTextField jTextFieldNodeType;
    private javax.swing.JTextField jTextFieldRestingStatus;
    private javax.swing.JTextField jTextFieldStatus;
    private java.awt.List listNodeList;
    private java.awt.List listRules;
    // End of variables declaration//GEN-END:variables
}
