/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.pseudocell.gui.tests;

import org.pseudocell.gui.cards.*;

/**
 *
 * @author ViníciusPierdoná
 */
public class ModelNodeStimulation extends javax.swing.JPanel {

    /**
     * Creates new form NodeStimulation
     */
    public ModelNodeStimulation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelNodeStimulationScreen = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        JLabel_Title = new javax.swing.JLabel();
        JLabel_Subtitle = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        JSlider_Frequency = new javax.swing.JSlider();
        JButton_Save = new javax.swing.JButton();
        JLabel_Frequency = new javax.swing.JLabel();
        JButton_Reset = new javax.swing.JButton();
        JLabel_FrequencyOutput = new javax.swing.JLabel();
        JLabel_TargetNode = new javax.swing.JLabel();
        JTextField_TargetNode = new javax.swing.JTextField();
        JButton_Export = new javax.swing.JButton();
        JButton_Import = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        JLabel_Filter = new javax.swing.JLabel();
        JTextField_Filter = new javax.swing.JTextField();
        JButton_Filter = new javax.swing.JButton();
        JLabel_NodeList = new javax.swing.JLabel();
        JList_NodeList = new java.awt.List();

        setMaximumSize(new java.awt.Dimension(900, 640));
        setMinimumSize(new java.awt.Dimension(900, 640));
        setPreferredSize(new java.awt.Dimension(900, 640));

        jPanelNodeStimulationScreen.setBackground(new java.awt.Color(56, 58, 77));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        JLabel_Title.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        JLabel_Title.setText("Node Stimulation");

        JLabel_Subtitle.setBackground(new java.awt.Color(204, 204, 255));
        JLabel_Subtitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JLabel_Subtitle.setText("Create disturbances in the network and set how often nodes will be activated.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLabel_Subtitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLabel_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(JLabel_Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLabel_Subtitle)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));

        JSlider_Frequency.setBackground(new java.awt.Color(69, 71, 95));
        JSlider_Frequency.setMajorTickSpacing(1);
        JSlider_Frequency.setMinimum(1);
        JSlider_Frequency.setMinorTickSpacing(1);
        JSlider_Frequency.setValue(10);
        JSlider_Frequency.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                JSlider_FrequencyStateChanged(evt);
            }
        });

        JButton_Save.setBackground(new java.awt.Color(126, 129, 161));
        JButton_Save.setForeground(new java.awt.Color(51, 51, 51));
        JButton_Save.setText("Save");
        JButton_Save.setBorderPainted(false);
        JButton_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_SaveActionPerformed(evt);
            }
        });

        JLabel_Frequency.setBackground(new java.awt.Color(204, 204, 255));
        JLabel_Frequency.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JLabel_Frequency.setText("Frequency of stimulation:");

        JButton_Reset.setBackground(new java.awt.Color(126, 129, 161));
        JButton_Reset.setForeground(new java.awt.Color(51, 51, 51));
        JButton_Reset.setText("Reset");
        JButton_Reset.setBorderPainted(false);
        JButton_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_ResetActionPerformed(evt);
            }
        });

        JLabel_FrequencyOutput.setBackground(new java.awt.Color(204, 204, 255));
        JLabel_FrequencyOutput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JLabel_FrequencyOutput.setText("0");

        JLabel_TargetNode.setBackground(new java.awt.Color(204, 204, 255));
        JLabel_TargetNode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JLabel_TargetNode.setText("Target Node");

        JTextField_TargetNode.setBackground(new java.awt.Color(69, 71, 95));
        JTextField_TargetNode.setForeground(new java.awt.Color(255, 255, 255));

        JButton_Export.setBackground(new java.awt.Color(126, 129, 161));
        JButton_Export.setForeground(new java.awt.Color(51, 51, 51));
        JButton_Export.setText("Export Configurations");
        JButton_Export.setBorderPainted(false);
        JButton_Export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_ExportActionPerformed(evt);
            }
        });

        JButton_Import.setBackground(new java.awt.Color(126, 129, 161));
        JButton_Import.setForeground(new java.awt.Color(51, 51, 51));
        JButton_Import.setText("Import Configurations");
        JButton_Import.setBorderPainted(false);
        JButton_Import.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_ImportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(JLabel_Frequency)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JLabel_FrequencyOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(JLabel_TargetNode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JSlider_Frequency, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JTextField_TargetNode)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(JButton_Import, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(JButton_Export, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(82, 82, 82)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JButton_Save, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JButton_Reset, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabel_TargetNode)
                .addGap(0, 0, 0)
                .addComponent(JTextField_TargetNode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabel_Frequency)
                    .addComponent(JLabel_FrequencyOutput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JSlider_Frequency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JButton_Export)
                    .addComponent(JButton_Save))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JButton_Reset)
                    .addComponent(JButton_Import))
                .addContainerGap())
        );

        JLabel_Filter.setBackground(new java.awt.Color(0, 0, 0));
        JLabel_Filter.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JLabel_Filter.setText("Filter");

        JTextField_Filter.setBackground(new java.awt.Color(69, 71, 95));
        JTextField_Filter.setForeground(new java.awt.Color(255, 255, 255));

        JButton_Filter.setBackground(new java.awt.Color(126, 129, 161));
        JButton_Filter.setForeground(new java.awt.Color(51, 51, 51));
        JButton_Filter.setText("Filter");
        JButton_Filter.setBorderPainted(false);
        JButton_Filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_FilterActionPerformed(evt);
            }
        });

        JLabel_NodeList.setBackground(new java.awt.Color(0, 0, 0));
        JLabel_NodeList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JLabel_NodeList.setText("Node List");

        JList_NodeList.setBackground(new java.awt.Color(69, 71, 95));
        JList_NodeList.setForeground(new java.awt.Color(255, 255, 255));
        JList_NodeList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JList_NodeListMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(JTextField_Filter, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JButton_Filter))
                    .addComponent(JList_NodeList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLabel_Filter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLabel_NodeList, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabel_Filter)
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTextField_Filter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JButton_Filter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLabel_NodeList)
                .addGap(0, 0, 0)
                .addComponent(JList_NodeList, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelNodeStimulationScreenLayout = new javax.swing.GroupLayout(jPanelNodeStimulationScreen);
        jPanelNodeStimulationScreen.setLayout(jPanelNodeStimulationScreenLayout);
        jPanelNodeStimulationScreenLayout.setHorizontalGroup(
            jPanelNodeStimulationScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNodeStimulationScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelNodeStimulationScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelNodeStimulationScreenLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelNodeStimulationScreenLayout.setVerticalGroup(
            jPanelNodeStimulationScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNodeStimulationScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelNodeStimulationScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 178, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanelNodeStimulationScreen, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelNodeStimulationScreen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JList_NodeListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JList_NodeListMouseClicked
        Node selectedNode = nodesDisplayed.get(JList_NodeList.getSelectedIndex());
        JTextField_TargetNode.setText(selectedNode.getName());
    }//GEN-LAST:event_JList_NodeListMouseClicked

    private void JButton_FilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_FilterActionPerformed
        JList_NodeList.removeAll();
        filterNodes(JTextField_Filter.getText(), JList_NodeList);
    }//GEN-LAST:event_JButton_FilterActionPerformed

    private void JButton_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_ResetActionPerformed
        int dialogResult = JOptionPane.showConfirmDialog (null, "This action will remove the current stimulus. Are you sure you want to proceed?","Warning",JOptionPane.YES_NO_OPTION);
        if(dialogResult == JOptionPane.YES_OPTION){
            configNodeStimulation.stimulatedNode = "";
            configNodeStimulation.stimulatedNodeFrequency = 10;
            JTextField_TargetNode.setText(configNodeStimulation.stimulatedNode);
            JLabel_FrequencyOutput.setText(String.valueOf(configNodeStimulation.stimulatedNodeFrequency));
            JSlider_Frequency.setValue(configNodeStimulation.stimulatedNodeFrequency);
        }
    }//GEN-LAST:event_JButton_ResetActionPerformed

    private void JButton_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_SaveActionPerformed
        if (JTextField_TargetNode.getText() == null || JTextField_TargetNode.getText() == "") {
            configNodeStimulation.stimulatedNode = "";
        } else {
            configNodeStimulation.stimulatedNode = JTextField_TargetNode.getText();
        }
        configNodeStimulation.stimulatedNodeFrequency = JSlider_Frequency.getValue();
        if (configNodeStimulation.saveConfigs() == true) {
            JOptionPane.showMessageDialog(rootPane, "Node stimulation settings saved successfully.", "Save Configurations", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(rootPane, "[ERROR] There was an error trying to save the node stimulation settings.", "Save Configurations", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_JButton_SaveActionPerformed

    private void JSlider_FrequencyStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_JSlider_FrequencyStateChanged
        JLabel_FrequencyOutput.setText(String.valueOf(JSlider_Frequency.getValue()));
        setVisible(true);
    }//GEN-LAST:event_JSlider_FrequencyStateChanged

    private void JButton_ExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_ExportActionPerformed
        if (JTextField_TargetNode.getText() == null || JTextField_TargetNode.getText() == "") {
            configNodeStimulation.stimulatedNode = "";
        } else {
            configNodeStimulation.stimulatedNode = JTextField_TargetNode.getText();
        }
        configNodeStimulation.stimulatedNodeFrequency = JSlider_Frequency.getValue();
        if (configNodeStimulation.saveConfigs() == true) {
            JOptionPane.showMessageDialog(rootPane, "Node stimulation settings saved successfully.", "Save Configurations", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(rootPane, "[ERROR] There was an error trying to save the node stimulation settings.", "Save Configurations", JOptionPane.ERROR_MESSAGE);
        }
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile() ;
            configNodeStimulation.saveConfigs(file);
            JOptionPane.showMessageDialog(rootPane, "File saved successfully.","File Saved", JOptionPane.INFORMATION_MESSAGE);
        } else {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_JButton_ExportActionPerformed

    private void JButton_ImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_ImportActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogType(javax.swing.JFileChooser.OPEN_DIALOG);
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            configNodeStimulation.loadConfigs(file);
            initNSComponents();
            JOptionPane.showMessageDialog(rootPane, "File imported successfully.","Successful Import", JOptionPane.INFORMATION_MESSAGE);
        } else {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_JButton_ImportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButton_Export;
    private javax.swing.JButton JButton_Filter;
    private javax.swing.JButton JButton_Import;
    private javax.swing.JButton JButton_Reset;
    private javax.swing.JButton JButton_Save;
    private javax.swing.JLabel JLabel_Filter;
    private javax.swing.JLabel JLabel_Frequency;
    private javax.swing.JLabel JLabel_FrequencyOutput;
    private javax.swing.JLabel JLabel_NodeList;
    private javax.swing.JLabel JLabel_Subtitle;
    private javax.swing.JLabel JLabel_TargetNode;
    private javax.swing.JLabel JLabel_Title;
    private java.awt.List JList_NodeList;
    private javax.swing.JSlider JSlider_Frequency;
    private javax.swing.JTextField JTextField_Filter;
    private javax.swing.JTextField JTextField_TargetNode;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelNodeStimulationScreen;
    // End of variables declaration//GEN-END:variables
}
