/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.pseudocell.gui.tests;

import java.awt.Color;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.io.File;
import java.io.IOException;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.TransformerException;
import org.pseudocell.core.NetworkFactory;
import org.pseudocell.core.nodes.Metabolite;
import org.pseudocell.core.nodes.Node;
import org.pseudocell.core.persistence.XMLNetworkReader;
import org.pseudocell.core.persistence.XMLNetworkWriter;
import org.pseudocell.config.Config;
import org.pseudocell.gui.nodes.CreateKnockout;
import org.pseudocell.gui.nodes.CreateModification;
import org.pseudocell.gui.nodes.EditModification;
import org.pseudocell.gui.utils.NodeFilter;
import org.xml.sax.SAXException;

/**
 *
 * @author ViníciusPierdoná
 */
public class ModelNodeConfigurations extends JPanel {

    private static final int TYPE_PROTEINGENE = 1;
    private static final int TYPE_METABOLITE = 2;
    private static final int TYPE_OTHER = 3;
    private static final int TYPE_MIRNA = 4;
    private static final int TYPE_DRUG = 5;

    NetworkFactory networkFactory;
    Config configurations;
    List<Node> nodeList, displayedNodes;
    NodeFilter nodeFilter;
    Node selectedNode;

    Color colorBlock;
    Color colorEnabled;

    /**
     * Creates new form NodeConfigurations
     *
     * @param configurations
     * @param nodeList
     */
    public ModelNodeConfigurations(Config configurations, List<Node> nodeList) {
        initComponents();

        this.configurations = configurations;
        this.nodeList = nodeList;
        this.networkFactory = new NetworkFactory();
        this.nodeFilter = new NodeFilter();

        colorBlock = new Color(53, 55, 71);
        colorEnabled = new Color(69, 71, 95);

        // Create a listener to control the methods needed when shown or hidden the card
        addComponentListener(new ComponentAdapter() {
            @Override
            public void componentHidden(ComponentEvent evt) {
                hidden();
            }

            @Override
            public void componentShown(ComponentEvent evt) {
                shown();
            }
        });
    }

    public void hidden() {

    }

    public void shown() {
        setComponents();
    }

    public void setComponents() {
        displayedNodes = nodeFilter.filterNodes(listNodesList, nodeList, null);
        JTextField_Name.setEditable(false);
        JTextField_Type.setEditable(false);
        JTextField_Name.setBackground(colorBlock);
        JTextField_Type.setBackground(colorBlock);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNCFilter2 = new javax.swing.JLabel();
        jLabelNCFilter5 = new javax.swing.JLabel();
        jPanelNodeConfigurationsScreen = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        JLabel_Title = new javax.swing.JLabel();
        JLabel_Subtitle1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        JLabel_Filter = new javax.swing.JLabel();
        JTextField_Filter = new javax.swing.JTextField();
        JButton_Filter = new javax.swing.JButton();
        JButton_Knockout = new javax.swing.JButton();
        JLabel_NodesList = new javax.swing.JLabel();
        listNodesList = new java.awt.List();
        jPanel3 = new javax.swing.JPanel();
        JTextField_RestingStatus = new javax.swing.JTextField();
        JLabel_SubTitle2 = new javax.swing.JLabel();
        JComboBox_Modifications = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        JButton_Save = new javax.swing.JButton();
        JLabel_MaxValue = new javax.swing.JLabel();
        JTextField_Status = new javax.swing.JTextField();
        JTextField_MinValue = new javax.swing.JTextField();
        JLabel_Name = new javax.swing.JLabel();
        JLabel_Income = new javax.swing.JLabel();
        JLabel_Status = new javax.swing.JLabel();
        JTextField_MaxValue = new javax.swing.JTextField();
        JLabel_RestingStatus = new javax.swing.JLabel();
        JTextField_Type = new javax.swing.JTextField();
        JTextField_Name = new javax.swing.JTextField();
        JLabel_Modifications = new javax.swing.JLabel();
        JTextField_Income = new javax.swing.JTextField();
        JLabel_MinValue = new javax.swing.JLabel();
        JButton_EditMod = new javax.swing.JButton();
        JButton_AddMod = new javax.swing.JButton();
        JLabel_Type = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        JButton_ExportNodes = new javax.swing.JButton();
        JButton_ImportNodes = new javax.swing.JButton();
        JButton_AddNode = new javax.swing.JButton();
        JButton_Reset = new javax.swing.JButton();

        jLabelNCFilter2.setBackground(new java.awt.Color(204, 204, 255));
        jLabelNCFilter2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNCFilter2.setForeground(new java.awt.Color(204, 204, 255));
        jLabelNCFilter2.setText("Filter");

        jLabelNCFilter5.setBackground(new java.awt.Color(204, 204, 255));
        jLabelNCFilter5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNCFilter5.setForeground(new java.awt.Color(204, 204, 255));
        jLabelNCFilter5.setText("Filter");

        setMaximumSize(new java.awt.Dimension(980, 650));
        setMinimumSize(new java.awt.Dimension(980, 650));
        setPreferredSize(new java.awt.Dimension(980, 650));

        jPanelNodeConfigurationsScreen.setBackground(new java.awt.Color(204, 204, 255));
        jPanelNodeConfigurationsScreen.setMaximumSize(new java.awt.Dimension(650, 720));
        jPanelNodeConfigurationsScreen.setPreferredSize(new java.awt.Dimension(650, 720));

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));

        JLabel_Title.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        JLabel_Title.setText("Node Configurations");

        JLabel_Subtitle1.setBackground(new java.awt.Color(204, 204, 255));
        JLabel_Subtitle1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JLabel_Subtitle1.setText("Edit key node settings such as their initial state or knockout specific nodes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLabel_Subtitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLabel_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(JLabel_Title)
                .addGap(6, 6, 6)
                .addComponent(JLabel_Subtitle1)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        JLabel_Filter.setBackground(new java.awt.Color(204, 204, 255));
        JLabel_Filter.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JLabel_Filter.setText("Filter");

        JTextField_Filter.setBackground(new java.awt.Color(69, 71, 95));
        JTextField_Filter.setForeground(new java.awt.Color(255, 255, 255));

        JButton_Filter.setBackground(new java.awt.Color(126, 129, 161));
        JButton_Filter.setForeground(new java.awt.Color(51, 51, 51));
        JButton_Filter.setText("Filter");
        JButton_Filter.setBorderPainted(false);
        JButton_Filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_FilterActionPerformed(evt);
            }
        });

        JButton_Knockout.setBackground(new java.awt.Color(126, 129, 161));
        JButton_Knockout.setForeground(new java.awt.Color(51, 51, 51));
        JButton_Knockout.setText("Create a knockout");
        JButton_Knockout.setBorderPainted(false);
        JButton_Knockout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_KnockoutActionPerformed(evt);
            }
        });

        JLabel_NodesList.setBackground(new java.awt.Color(204, 204, 255));
        JLabel_NodesList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JLabel_NodesList.setText("Nodes List");

        listNodesList.setBackground(new java.awt.Color(69, 71, 95));
        listNodesList.setForeground(new java.awt.Color(255, 255, 255));
        listNodesList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listNodesListMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JLabel_Filter, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLabel_NodesList, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(listNodesList, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(JTextField_Filter, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JButton_Filter)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                                .addComponent(JButton_Knockout, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabel_Filter)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTextField_Filter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JButton_Filter)
                    .addComponent(JButton_Knockout))
                .addGap(6, 6, 6)
                .addComponent(JLabel_NodesList)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(listNodesList, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));

        JTextField_RestingStatus.setBackground(new java.awt.Color(69, 71, 95));
        JTextField_RestingStatus.setForeground(new java.awt.Color(255, 255, 255));

        JLabel_SubTitle2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        JLabel_SubTitle2.setText("Edit a node of the network");

        JComboBox_Modifications.setBackground(new java.awt.Color(69, 71, 95));
        JComboBox_Modifications.setForeground(new java.awt.Color(255, 255, 255));

        JButton_Save.setBackground(new java.awt.Color(126, 129, 161));
        JButton_Save.setForeground(new java.awt.Color(51, 51, 51));
        JButton_Save.setText("Save Node Edition");
        JButton_Save.setBorderPainted(false);
        JButton_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_SaveActionPerformed(evt);
            }
        });

        JLabel_MaxValue.setBackground(new java.awt.Color(204, 204, 255));
        JLabel_MaxValue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JLabel_MaxValue.setText("Metabolic max. value");

        JTextField_Status.setBackground(new java.awt.Color(69, 71, 95));
        JTextField_Status.setForeground(new java.awt.Color(255, 255, 255));

        JTextField_MinValue.setBackground(new java.awt.Color(69, 71, 95));
        JTextField_MinValue.setForeground(new java.awt.Color(255, 255, 255));

        JLabel_Name.setBackground(new java.awt.Color(204, 204, 255));
        JLabel_Name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JLabel_Name.setText("Name");

        JLabel_Income.setBackground(new java.awt.Color(204, 204, 255));
        JLabel_Income.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JLabel_Income.setText("Metabolic income");

        JLabel_Status.setBackground(new java.awt.Color(204, 204, 255));
        JLabel_Status.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JLabel_Status.setText("Initial status");

        JTextField_MaxValue.setBackground(new java.awt.Color(69, 71, 95));
        JTextField_MaxValue.setForeground(new java.awt.Color(255, 255, 255));

        JLabel_RestingStatus.setBackground(new java.awt.Color(204, 204, 255));
        JLabel_RestingStatus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JLabel_RestingStatus.setText("Resting status");

        JTextField_Type.setBackground(new java.awt.Color(69, 71, 95));
        JTextField_Type.setForeground(new java.awt.Color(255, 255, 255));

        JTextField_Name.setBackground(new java.awt.Color(69, 71, 95));
        JTextField_Name.setForeground(new java.awt.Color(255, 255, 255));

        JLabel_Modifications.setBackground(new java.awt.Color(204, 204, 255));
        JLabel_Modifications.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JLabel_Modifications.setText("Node modifications");

        JTextField_Income.setBackground(new java.awt.Color(69, 71, 95));
        JTextField_Income.setForeground(new java.awt.Color(255, 255, 255));

        JLabel_MinValue.setBackground(new java.awt.Color(204, 204, 255));
        JLabel_MinValue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JLabel_MinValue.setText("Metabolic min. value");

        JButton_EditMod.setBackground(new java.awt.Color(126, 129, 161));
        JButton_EditMod.setForeground(new java.awt.Color(51, 51, 51));
        JButton_EditMod.setText("Edit Mod");
        JButton_EditMod.setBorderPainted(false);
        JButton_EditMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_EditModActionPerformed(evt);
            }
        });

        JButton_AddMod.setBackground(new java.awt.Color(126, 129, 161));
        JButton_AddMod.setForeground(new java.awt.Color(51, 51, 51));
        JButton_AddMod.setText("Add Mod");
        JButton_AddMod.setBorderPainted(false);
        JButton_AddMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_AddModActionPerformed(evt);
            }
        });

        JLabel_Type.setBackground(new java.awt.Color(204, 204, 255));
        JLabel_Type.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JLabel_Type.setText("Node Type");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(JLabel_SubTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(JButton_AddMod, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JButton_EditMod, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(JLabel_Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JTextField_Name)
                            .addComponent(JLabel_Modifications, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                            .addComponent(JTextField_RestingStatus)
                            .addComponent(JLabel_RestingStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JLabel_Status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JTextField_Status)
                            .addComponent(JComboBox_Modifications, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(JButton_Save))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(JTextField_MinValue)
                                .addComponent(JTextField_Income)
                                .addComponent(JTextField_Type)
                                .addComponent(JLabel_Income, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JLabel_MinValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JLabel_Type, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(JTextField_MaxValue)
                                .addComponent(JLabel_MaxValue, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLabel_SubTitle2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLabel_Name)
                    .addComponent(JLabel_Type))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTextField_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTextField_Type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLabel_Status)
                    .addComponent(JLabel_Income))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTextField_Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTextField_Income, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLabel_RestingStatus)
                    .addComponent(JLabel_MinValue))
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTextField_RestingStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTextField_MinValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(JLabel_Modifications)
                        .addGap(0, 0, 0)
                        .addComponent(JComboBox_Modifications, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(JLabel_MaxValue)
                        .addGap(0, 0, 0)
                        .addComponent(JTextField_MaxValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JButton_AddMod)
                            .addComponent(JButton_EditMod)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JButton_Save)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 204, 255));

        JButton_ExportNodes.setBackground(new java.awt.Color(126, 129, 161));
        JButton_ExportNodes.setForeground(new java.awt.Color(51, 51, 51));
        JButton_ExportNodes.setText("Export Nodes");
        JButton_ExportNodes.setBorderPainted(false);
        JButton_ExportNodes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_ExportNodesActionPerformed(evt);
            }
        });

        JButton_ImportNodes.setBackground(new java.awt.Color(126, 129, 161));
        JButton_ImportNodes.setForeground(new java.awt.Color(51, 51, 51));
        JButton_ImportNodes.setText("Import Nodes");
        JButton_ImportNodes.setBorderPainted(false);
        JButton_ImportNodes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_ImportNodesActionPerformed(evt);
            }
        });

        JButton_AddNode.setBackground(new java.awt.Color(126, 129, 161));
        JButton_AddNode.setForeground(new java.awt.Color(51, 51, 51));
        JButton_AddNode.setText("Create Node");
        JButton_AddNode.setBorderPainted(false);
        JButton_AddNode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_AddNodeActionPerformed(evt);
            }
        });

        JButton_Reset.setBackground(new java.awt.Color(126, 129, 161));
        JButton_Reset.setForeground(new java.awt.Color(51, 51, 51));
        JButton_Reset.setText("Reset Nodes");
        JButton_Reset.setBorderPainted(false);
        JButton_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_ResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(JButton_ExportNodes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JButton_ImportNodes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JButton_AddNode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JButton_Reset))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 7, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JButton_AddNode)
                        .addComponent(JButton_Reset))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JButton_ExportNodes)
                            .addComponent(JButton_ImportNodes))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout jPanelNodeConfigurationsScreenLayout = new javax.swing.GroupLayout(jPanelNodeConfigurationsScreen);
        jPanelNodeConfigurationsScreen.setLayout(jPanelNodeConfigurationsScreenLayout);
        jPanelNodeConfigurationsScreenLayout.setHorizontalGroup(
            jPanelNodeConfigurationsScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNodeConfigurationsScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelNodeConfigurationsScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelNodeConfigurationsScreenLayout.setVerticalGroup(
            jPanelNodeConfigurationsScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNodeConfigurationsScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelNodeConfigurationsScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 360, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelNodeConfigurationsScreen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JButton_FilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_FilterActionPerformed
        listNodesList.removeAll();
        displayedNodes = nodeFilter.filterNodes(listNodesList, nodeList, JTextField_Filter.getText());
    }//GEN-LAST:event_JButton_FilterActionPerformed

    private void listNodesListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listNodesListMouseClicked
        // Ensures the item will only be accessed on the second click
        if (evt.getClickCount() == 2) {
            int selectedIndex = listNodesList.getSelectedIndex();
            selectedNode = displayedNodes.get(selectedIndex);
            boolean metabolite = false;
            //
            JTextField_Name.setText(selectedNode.getName());
            JTextField_Status.setText(String.valueOf(selectedNode.getStatus()));
            JTextField_RestingStatus.setText(String.valueOf(selectedNode.getRestingStatus()));
            // Checks if the node has modifications and, if so, populates the ComboBox
            JComboBox_Modifications.removeAllItems();
            if (!selectedNode.getNodeModifications().isEmpty()) {
                for (int i = 0; i < selectedNode.getNodeModifications().size(); i++) {
                    JComboBox_Modifications.addItem(selectedNode.getNodeModifications().get(i).getName());
                }
            } else {
                JComboBox_Modifications.addItem("<none>");
            }
            // Set node type
            switch (selectedNode.getType()) {
                case TYPE_PROTEINGENE:
                    JTextField_Type.setText("Protein/Gene");
                    break;
                case TYPE_METABOLITE:
                    JTextField_Type.setText("Metabolite");
                    break;
                case TYPE_OTHER:
                    JTextField_Type.setText("Other");
                    break;
                case TYPE_MIRNA:
                    JTextField_Type.setText("miRNA");
                    ;
                    break;
                case TYPE_DRUG:
                    JTextField_Type.setText("Drug");
                    break;
                default:
                    throw new AssertionError();
            }
            // If the node is a metabolite, populate specific fields for metabolites. If not, block these fields.
            if (selectedNode.getType() == 2) {
                JTextField_Income.setText(String.valueOf(((Metabolite) selectedNode).getIncome()));
                JTextField_MinValue.setText(String.valueOf(((Metabolite) selectedNode).getMinValue()));
                JTextField_MaxValue.setText(String.valueOf(((Metabolite) selectedNode).getMaxValue()));
                metabolite = true;
            }

            JTextField_Income.setEditable(metabolite);
            JTextField_MinValue.setEditable(metabolite);
            JTextField_MaxValue.setEditable(metabolite);
            JTextField_RestingStatus.setEditable(!metabolite);
            setFieldColor(metabolite);
        }
    }//GEN-LAST:event_listNodesListMouseClicked

    private void JButton_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_ResetActionPerformed
        int dialogResult = JOptionPane.showConfirmDialog(null, "This action will restore the nodes, including their rules, to those provided by default. Would you like to proceed?", "Warning", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
            configurations.networkSourceInputType = "default";
            nodeList = networkFactory.createNetwork(configurations).getDefaultNodes();
            setComponents();
        }
    }//GEN-LAST:event_JButton_ResetActionPerformed

    private void JButton_ExportNodesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_ExportNodesActionPerformed
        int dialogResult = JOptionPane.showConfirmDialog(null, "This action will save any changes made to the nodes. Would you like to proceed?", "Warning", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
            int returnVal = fileChooser.showOpenDialog(this);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                File file = fileChooser.getSelectedFile();
                try {
                    // Export node settings
                    XMLNetworkWriter.exportNodeList(file.getAbsolutePath(), nodeList);
                    // Concurrently saves node settings to temporary file
                    XMLNetworkWriter.exportNodeList(configurations.networkSourceFileName, nodeList);
                    // Ensures that the system takes into account user-placed node configurations
                    configurations.networkSourceInputType = "xml";
                    JOptionPane.showMessageDialog(this, "Export completed successfully.", "Successful Import", JOptionPane.INFORMATION_MESSAGE);
                } catch (ParserConfigurationException | IOException | SAXException | TransformerException ex) {
                    java.util.logging.Logger.getLogger(ModelNodeConfigurations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
            } else {
                System.out.println("File access cancelled by user.");
            }
        }
    }//GEN-LAST:event_JButton_ExportNodesActionPerformed

    private void JButton_ImportNodesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_ImportNodesActionPerformed
        int dialogResult = JOptionPane.showConfirmDialog(null, "This action will replace the current network, including its rules, with the chosen network. Would you like to proceed?", "Warning", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setDialogType(javax.swing.JFileChooser.OPEN_DIALOG);
            int returnVal = fileChooser.showOpenDialog(this);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                try {
                    File file = fileChooser.getSelectedFile();
                    // Replaces the list of current nodes with those submitted by the user.
                    nodeList = XMLNetworkReader.importNodeList(file);
                    // Simultaneously replaces the nodes' local file with those submitted by the user.
                    XMLNetworkWriter.exportNodeList(configurations.networkSourceFileName, nodeList);
                    configurations.networkSourceInputType = "xml";
                    setComponents();
                    JOptionPane.showMessageDialog(this, "File imported successfully.", "Successful Import", JOptionPane.INFORMATION_MESSAGE);
                } catch (ParserConfigurationException | IOException | SAXException | TransformerException ex) {
                    java.util.logging.Logger.getLogger(ModelNodeConfigurations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
            } else {
                System.out.println("File access cancelled by user.");
            }
        }
    }//GEN-LAST:event_JButton_ImportNodesActionPerformed

    private void JButton_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_SaveActionPerformed
        int dialogResult = JOptionPane.showConfirmDialog(null, "This action will save any changes made to the nodes. Would you like to proceed?", "Warning", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
            // Checks if a node has been selected by the user.
            if (JTextField_Name.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "[ERROR] No nodes were selected.", "Error - Empty Node", JOptionPane.ERROR_MESSAGE);
                return;
            }
            selectedNode.setStatus(Double.valueOf(JTextField_Status.getText()));
            selectedNode.setRestingStatus(Double.valueOf(JTextField_RestingStatus.getText()));
            selectedNode.setStatus(Double.valueOf(JTextField_Status.getText()));
            if (selectedNode.getType() == 2) {
                ((Metabolite) selectedNode).setIncome(Double.valueOf(JTextField_Income.getText()));
                ((Metabolite) selectedNode).setMinValue(Double.valueOf(JTextField_MinValue.getText()));
                ((Metabolite) selectedNode).setMaxValue(Double.valueOf(JTextField_MaxValue.getText()));
            }
            // Ensures that the network used in the execution contains the changes made by the user.
            configurations.networkSourceInputType = "xml";
        }
    }//GEN-LAST:event_JButton_SaveActionPerformed

    private void JButton_EditModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_EditModActionPerformed
        // Checks if a node has been selected by the user.
        if (JTextField_Name.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "[ERROR] No nodes were selected.", "Error - Empty Node", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Checks if the node has any modifications to be edited.
        if (JComboBox_Modifications.getItemAt(0).equals("<none>")) {
            JOptionPane.showMessageDialog(this, "[ERROR] This node has no modifications available for editing.", "Error - Empty Node", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int modificationIndex = JComboBox_Modifications.getSelectedIndex();
        EditModification frame = new EditModification(configurations, nodeList, selectedNode, modificationIndex);
        frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        frame.setVisible(true);
    }//GEN-LAST:event_JButton_EditModActionPerformed

    private void JButton_AddModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_AddModActionPerformed
        // Checks if a node has been selected by the user.
        if (JTextField_Name.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "[ERROR] No nodes were selected.", "Error - Empty Node", JOptionPane.ERROR_MESSAGE);
            return;
        }
        CreateModification frame = new CreateModification(configurations, selectedNode);
        frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        frame.setVisible(true);
    }//GEN-LAST:event_JButton_AddModActionPerformed

    private void JButton_KnockoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_KnockoutActionPerformed
        CreateKnockout frame = new CreateKnockout(configurations, nodeList);
        frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        frame.setVisible(true);
    }//GEN-LAST:event_JButton_KnockoutActionPerformed

    private void JButton_AddNodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_AddNodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JButton_AddNodeActionPerformed

    public void setFieldColor(boolean metabolic) {
        if (metabolic) {
            JTextField_Income.setBackground(colorEnabled);
            JTextField_MinValue.setBackground(colorEnabled);
            JTextField_MaxValue.setBackground(colorEnabled);
            JTextField_RestingStatus.setBackground(colorBlock);

        } else {
            JTextField_Income.setBackground(colorBlock);
            JTextField_MinValue.setBackground(colorBlock);
            JTextField_MaxValue.setBackground(colorBlock);
            JTextField_RestingStatus.setBackground(colorEnabled);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButton_AddMod;
    private javax.swing.JButton JButton_AddNode;
    private javax.swing.JButton JButton_EditMod;
    private javax.swing.JButton JButton_ExportNodes;
    private javax.swing.JButton JButton_Filter;
    private javax.swing.JButton JButton_ImportNodes;
    private javax.swing.JButton JButton_Knockout;
    private javax.swing.JButton JButton_Reset;
    private javax.swing.JButton JButton_Save;
    private javax.swing.JComboBox<String> JComboBox_Modifications;
    private javax.swing.JLabel JLabel_Filter;
    private javax.swing.JLabel JLabel_Income;
    private javax.swing.JLabel JLabel_MaxValue;
    private javax.swing.JLabel JLabel_MinValue;
    private javax.swing.JLabel JLabel_Modifications;
    private javax.swing.JLabel JLabel_Name;
    private javax.swing.JLabel JLabel_NodesList;
    private javax.swing.JLabel JLabel_RestingStatus;
    private javax.swing.JLabel JLabel_Status;
    private javax.swing.JLabel JLabel_SubTitle2;
    private javax.swing.JLabel JLabel_Subtitle1;
    private javax.swing.JLabel JLabel_Title;
    private javax.swing.JLabel JLabel_Type;
    private javax.swing.JTextField JTextField_Filter;
    private javax.swing.JTextField JTextField_Income;
    private javax.swing.JTextField JTextField_MaxValue;
    private javax.swing.JTextField JTextField_MinValue;
    private javax.swing.JTextField JTextField_Name;
    private javax.swing.JTextField JTextField_RestingStatus;
    private javax.swing.JTextField JTextField_Status;
    private javax.swing.JTextField JTextField_Type;
    private javax.swing.JLabel jLabelNCFilter2;
    private javax.swing.JLabel jLabelNCFilter5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelNodeConfigurationsScreen;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private java.awt.List listNodesList;
    // End of variables declaration//GEN-END:variables
}
