/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.pseudocell.gui.tests;

import org.pseudocell.gui.nodes.*;
import java.awt.Color;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.util.List;
import javax.swing.JOptionPane;
import org.pseudocell.core.nodes.Node;
import org.pseudocell.core.nodes.NodeModification;
import org.pseudocell.core.utils.FindEdge;
import org.pseudocell.config.Config;

/**
 *
 * @author ViníciusPierdoná
 */
public class ModelEditModification extends javax.swing.JFrame {

    private static final int TYPE_PROTEINGENE = 1;
    private static final int TYPE_METABOLITE = 2;
    private static final int TYPE_OTHER = 3;
    private static final int TYPE_MIRNA = 4;
    private static final int TYPE_DRUG = 5;

    Config configurations;
    List<Node> nodeList;
    Node node;
    int modificationIndex;
    NodeModification modification;
    FindEdge findEdge;
    boolean nodeListModification;

    Color colorBlock;
    Color colorEnabled;

    /**
     * Creates new form ModificationEdit
     *
     * @param configurations
     * @param nodeList
     * @param node
     * @param modificationIndex
     */
    public ModelEditModification(Config configurations, List<Node> nodeList, Node node, int modificationIndex) {
        initComponents();

        this.configurations = configurations;
        this.nodeList = nodeList;
        this.node = node;
        this.modificationIndex = modificationIndex;
        this.findEdge = new FindEdge();
        this.nodeListModification = false;

        colorBlock = new Color(53, 55, 71);
        colorEnabled = new Color(69, 71, 95);

        // Create a listener to control the methods needed when shown or hidden the card
        addComponentListener(new ComponentAdapter() {
            @Override
            public void componentHidden(ComponentEvent evt) {
                hidden();
            }

            @Override
            public void componentShown(ComponentEvent evt) {
                shown();
            }
        });
    }

    public void hidden() {
        if (nodeListModification) {
            // If any nodes have been created, ensures that the network used in the execution contains the changes made by the user.
            configurations.networkSourceInputType = "xml";
        }
    }

    public void shown() {
        setComponents();
    }

    public void setComponents() {
        jTextFieldNodeName.setText(node.getName());
        switch (node.getType()) {
            case TYPE_PROTEINGENE:
                jTextFieldNodeType.setText("Protein/Gene");
                break;
            case TYPE_METABOLITE:
                jTextFieldNodeType.setText("Metabolite");
                break;
            case TYPE_OTHER:
                jTextFieldNodeType.setText("Other");
                break;
            case TYPE_MIRNA:
                jTextFieldNodeType.setText("miRNA");
                ;
                break;
            case TYPE_DRUG:
                jTextFieldNodeType.setText("Drug");
                break;
            default:
                throw new AssertionError();
        }
        jTextFieldNodeName.setEditable(false);
        jTextFieldNodeType.setEditable(false);
        jTextFieldNodeName.setBackground(colorBlock);
        jTextFieldNodeType.setBackground(colorBlock);
        if (!node.getNodeModifications().isEmpty()) {
            for (int i = 0; i < node.getNodeModifications().size(); i++) {
                modification = node.getNodeModifications().get(i);
                listMod.add("[Mod] " + modification.getName() + " - Resting Status: " + modification.getRestingStatus());
            }
        }
        setModificationFields(modificationIndex);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelModificationEditScreen = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabelSubtitle = new javax.swing.JLabel();
        jLabelNodeName = new javax.swing.JLabel();
        jTextFieldNodeName = new javax.swing.JTextField();
        jLabelNodeType = new javax.swing.JLabel();
        jTextFieldNodeType = new javax.swing.JTextField();
        jButtonCancel = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jLabelTitle = new javax.swing.JLabel();
        jLabelModName = new javax.swing.JLabel();
        jTextFieldModName = new javax.swing.JTextField();
        jLabelModStatus = new javax.swing.JLabel();
        jTextFieldModStatus = new javax.swing.JTextField();
        jLabelModList = new javax.swing.JLabel();
        jLabelModRestingStatus = new javax.swing.JLabel();
        jTextFieldRestingStatus = new javax.swing.JTextField();
        listMod = new java.awt.List();
        jButtonDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelModificationEditScreen.setBackground(new java.awt.Color(56, 58, 77));
        jPanelModificationEditScreen.setMaximumSize(new java.awt.Dimension(680, 480));
        jPanelModificationEditScreen.setPreferredSize(new java.awt.Dimension(680, 480));

        jLabelSubtitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelSubtitle.setForeground(new java.awt.Color(204, 204, 255));
        jLabelSubtitle.setText("Edit a modification");

        jLabelNodeName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNodeName.setForeground(new java.awt.Color(204, 204, 255));
        jLabelNodeName.setText("Node name");

        jTextFieldNodeName.setBackground(new java.awt.Color(69, 71, 95));
        jTextFieldNodeName.setForeground(new java.awt.Color(255, 255, 255));

        jLabelNodeType.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNodeType.setForeground(new java.awt.Color(204, 204, 255));
        jLabelNodeType.setText("Node type");

        jTextFieldNodeType.setBackground(new java.awt.Color(69, 71, 95));
        jTextFieldNodeType.setForeground(new java.awt.Color(255, 255, 255));

        jButtonCancel.setBackground(new java.awt.Color(126, 129, 161));
        jButtonCancel.setForeground(new java.awt.Color(51, 51, 51));
        jButtonCancel.setText("Cancel");
        jButtonCancel.setBorderPainted(false);
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonSave.setBackground(new java.awt.Color(126, 129, 161));
        jButtonSave.setForeground(new java.awt.Color(51, 51, 51));
        jButtonSave.setText("Save");
        jButtonSave.setBorderPainted(false);
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(204, 204, 255));
        jLabelTitle.setText("Edit Network");

        jLabelModName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelModName.setForeground(new java.awt.Color(204, 204, 255));
        jLabelModName.setText("Modification name");

        jTextFieldModName.setBackground(new java.awt.Color(69, 71, 95));
        jTextFieldModName.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldModName.setText("newModification");

        jLabelModStatus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelModStatus.setForeground(new java.awt.Color(204, 204, 255));
        jLabelModStatus.setText("Modification initial status");

        jTextFieldModStatus.setBackground(new java.awt.Color(69, 71, 95));
        jTextFieldModStatus.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldModStatus.setText("0.0");

        jLabelModList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelModList.setForeground(new java.awt.Color(204, 204, 255));
        jLabelModList.setText("Modifications list");

        jLabelModRestingStatus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelModRestingStatus.setForeground(new java.awt.Color(204, 204, 255));
        jLabelModRestingStatus.setText("Modification resting status");

        jTextFieldRestingStatus.setBackground(new java.awt.Color(69, 71, 95));
        jTextFieldRestingStatus.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldRestingStatus.setText("0.0");

        listMod.setBackground(new java.awt.Color(69, 71, 95));
        listMod.setForeground(new java.awt.Color(255, 255, 255));
        listMod.setName(""); // NOI18N
        listMod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listModMouseClicked(evt);
            }
        });

        jButtonDelete.setBackground(new java.awt.Color(126, 129, 161));
        jButtonDelete.setForeground(new java.awt.Color(51, 51, 51));
        jButtonDelete.setText("Delete");
        jButtonDelete.setBorderPainted(false);
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelModificationEditScreenLayout = new javax.swing.GroupLayout(jPanelModificationEditScreen);
        jPanelModificationEditScreen.setLayout(jPanelModificationEditScreenLayout);
        jPanelModificationEditScreenLayout.setHorizontalGroup(
            jPanelModificationEditScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModificationEditScreenLayout.createSequentialGroup()
                .addGroup(jPanelModificationEditScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelModificationEditScreenLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelModificationEditScreenLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanelModificationEditScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelModificationEditScreenLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanelModificationEditScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanelModificationEditScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelModificationEditScreenLayout.createSequentialGroup()
                                            .addComponent(jLabelSubtitle)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabelTitle))
                                    .addGroup(jPanelModificationEditScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelNodeType)
                                        .addComponent(jTextFieldNodeType, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelModList)
                                        .addComponent(listMod, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanelModificationEditScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanelModificationEditScreenLayout.createSequentialGroup()
                                    .addComponent(jButtonSave)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonDelete)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonCancel))
                                .addGroup(jPanelModificationEditScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNodeName)
                                    .addComponent(jTextFieldNodeName, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelModName)
                                    .addComponent(jTextFieldModName, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelModStatus)
                                    .addComponent(jTextFieldModStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelModRestingStatus)
                                    .addComponent(jTextFieldRestingStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        jPanelModificationEditScreenLayout.setVerticalGroup(
            jPanelModificationEditScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModificationEditScreenLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelModificationEditScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelSubtitle)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelModificationEditScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelModificationEditScreenLayout.createSequentialGroup()
                        .addGroup(jPanelModificationEditScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNodeName)
                            .addComponent(jLabelNodeType))
                        .addGap(0, 0, 0)
                        .addComponent(jTextFieldNodeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelModificationEditScreenLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jTextFieldNodeType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(jPanelModificationEditScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelModificationEditScreenLayout.createSequentialGroup()
                        .addComponent(jLabelModName)
                        .addGap(0, 0, 0)
                        .addComponent(jTextFieldModName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelModStatus)
                        .addGap(0, 0, 0)
                        .addComponent(jTextFieldModStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelModRestingStatus)
                        .addGap(0, 0, 0)
                        .addComponent(jTextFieldRestingStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelModificationEditScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSave)
                            .addComponent(jButtonCancel)
                            .addComponent(jButtonDelete)))
                    .addGroup(jPanelModificationEditScreenLayout.createSequentialGroup()
                        .addComponent(jLabelModList)
                        .addGap(0, 0, 0)
                        .addComponent(listMod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(298, 298, 298))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelModificationEditScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelModificationEditScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        int dialogResult = JOptionPane.showConfirmDialog(null, "This action will edit this modification within the selected node. Would you like to proceed?", "Warning", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
            if (jTextFieldModName.getText().isBlank() | jTextFieldModStatus.getText().isBlank() | jTextFieldRestingStatus.getText().isBlank()) {
                JOptionPane.showMessageDialog(this, "[ERROR] All fields must be filled.", "Error - Empty Field", JOptionPane.ERROR_MESSAGE);
                return;
            }
            String modificationName = jTextFieldModName.getText();
            Double modificationStatus = Double.valueOf(jTextFieldModStatus.getText());
            Double modificationResting = Double.valueOf(jTextFieldRestingStatus.getText());
            modification = node.getNodeModifications().get(modificationIndex);
            modification.setName(modificationName);
            modification.setModificationStatus(modificationStatus);
            modification.setRestingStatus(modificationResting);
            nodeListModification = true;
            JOptionPane.showMessageDialog(rootPane, "Modification created successfully.", "Modification created", JOptionPane.INFORMATION_MESSAGE);
            listMod.removeAll();
            setComponents();
        }
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        int dialogResult = JOptionPane.showConfirmDialog(null, "Warning! This action will delete this modification from that node. Would you like to proceed?", "Warning", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
            if (jTextFieldModName.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "[ERROR] No modification has been selected.", "Error - Empty Field", JOptionPane.ERROR_MESSAGE);
                return;
            }
            // Check if the selected modification participates in any rules on the network.
            List<String> nodeEdge = findEdge.findModificationEdges(nodeList, jTextFieldModName.getText());
            if (nodeEdge.isEmpty()) {
                node.getNodeModifications().remove(node.getNodeModifications().get(modificationIndex));
                nodeListModification = true;
                // Update the interface
                listMod.removeAll();
                setComponents();
                jTextFieldModName.setText("");
                jTextFieldModStatus.setText("");
                jTextFieldRestingStatus.setText("");
            } else {
                String errorMessage = "";
                for (String edge : nodeEdge) {
                    errorMessage += "\n- " + edge;
                }
                JOptionPane.showMessageDialog(this, "[ERROR] The modification cannot be deleted because it is associated with the following nodes:\n"+errorMessage, "Error - Empty Node", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void listModMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listModMouseClicked
        if (evt.getClickCount() == 2) {
            int dialogResult = JOptionPane.showConfirmDialog(null, "You will lose any unsaved edits made to this modification. Would you like to proceed?", "Warning", JOptionPane.YES_NO_OPTION);
            if (dialogResult == JOptionPane.YES_OPTION) {
                modificationIndex = listMod.getSelectedIndex();
                setModificationFields(modificationIndex);
            }
        }
    }//GEN-LAST:event_listModMouseClicked

    public void setModificationFields(int modificationIndex) {
        modification = node.getNodeModifications().get(modificationIndex);
        jTextFieldModName.setText(modification.getName());
        jTextFieldModStatus.setText(String.valueOf(modification.getModificationStatus()));
        jTextFieldRestingStatus.setText(String.valueOf(modification.getRestingStatus()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabelModList;
    private javax.swing.JLabel jLabelModName;
    private javax.swing.JLabel jLabelModRestingStatus;
    private javax.swing.JLabel jLabelModStatus;
    private javax.swing.JLabel jLabelNodeName;
    private javax.swing.JLabel jLabelNodeType;
    private javax.swing.JLabel jLabelSubtitle;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanelModificationEditScreen;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField jTextFieldModName;
    private javax.swing.JTextField jTextFieldModStatus;
    private javax.swing.JTextField jTextFieldNodeName;
    private javax.swing.JTextField jTextFieldNodeType;
    private javax.swing.JTextField jTextFieldRestingStatus;
    private java.awt.List listMod;
    // End of variables declaration//GEN-END:variables
}
