/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.pseudocell.gui.tests;

import org.pseudocell.gui.cards.*;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.io.File;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.pseudocell.config.Config;
import org.pseudocell.gui.validation.FieldValidation;

/**
 *
 * @author ViníciusPierdoná
 */
public class ModelGeneralConfigurations extends javax.swing.JPanel {

    Config configurations;
    FieldValidation fieldValidation;

    /**
     * Creates new form GeneralConfigurations
     *
     * @param configurations
     */
    public ModelGeneralConfigurations(Config configurations) {
        initComponents();
        this.configurations = configurations;
        fieldValidation = new FieldValidation();
        
        // Create a listener to control the methods needed when shown or hidden the card
        addComponentListener(new ComponentAdapter() {
            @Override
            public void componentHidden(ComponentEvent evt) {
                hidden();
            }

            @Override
            public void componentShown(ComponentEvent evt) {
                shown();
            }
        });
    }
    
    public void shown() {
        setComponents();
    }

    public void hidden() {

    }

    private void setComponents() {
        JTextField_ProjectName.setText(configurations.projectName);
        JLabel_LastUpdateOutput.setText(Config.dateFormat.format(configurations.lastUpdate));
        JTextField_NodeSourceFile.setText(configurations.networkSourceFileName);
        JTextField_TickNumber.setText(configurations.numberOfTicks.toString());
        JTextField_NetworkNumber.setText(configurations.numberOfNetworks.toString());
        JTextField_SampleNumber.setText(configurations.numberOfSamples.toString());
        for(int i = 0;  i < JComboBox_NodeFileFormat.getItemCount(); i++) {
            String value = JComboBox_NodeFileFormat.getItemAt(i);
            if(value.equals(configurations.networkSourceInputType)){
                JComboBox_NodeFileFormat.setSelectedIndex(i);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelGeneralConfigurationsScreen = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        JLabel_Title = new javax.swing.JLabel();
        JLabel_Subtitle = new javax.swing.JLabel();
        JLabel_Important = new javax.swing.JLabel();
        JLabel_ImportantMessage1 = new javax.swing.JLabel();
        JLabel_ImportantMessage2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        JLabel_ProjectName = new javax.swing.JLabel();
        JTextField_ProjectName = new javax.swing.JTextField();
        JLabel_NetworkSourceFile = new javax.swing.JLabel();
        JTextField_NodeSourceFile = new javax.swing.JTextField();
        JLabel_LastUpdate = new javax.swing.JLabel();
        JLabel_LastUpdateOutput = new javax.swing.JLabel();
        JLabel_NetworkFileFormat = new javax.swing.JLabel();
        JComboBox_NodeFileFormat = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        JLabel_TickNumber = new javax.swing.JLabel();
        JTextField_TickNumber = new javax.swing.JTextField();
        JLabel_SampleNumber = new javax.swing.JLabel();
        JTextField_SampleNumber = new javax.swing.JTextField();
        JLabel_NetworkNumber = new javax.swing.JLabel();
        JTextField_NetworkNumber = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        JButton_Export = new javax.swing.JButton();
        JButton_Import = new javax.swing.JButton();
        JButton_Save = new javax.swing.JButton();
        JButton_Reset = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(980, 650));
        setMinimumSize(new java.awt.Dimension(980, 650));
        setPreferredSize(new java.awt.Dimension(980, 650));

        jPanelGeneralConfigurationsScreen.setBackground(new java.awt.Color(56, 58, 77));
        jPanelGeneralConfigurationsScreen.setMaximumSize(new java.awt.Dimension(650, 650));
        jPanelGeneralConfigurationsScreen.setMinimumSize(new java.awt.Dimension(650, 650));
        jPanelGeneralConfigurationsScreen.setPreferredSize(new java.awt.Dimension(650, 650));

        JLabel_Title.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        JLabel_Title.setText("General Configurations");

        JLabel_Subtitle.setBackground(new java.awt.Color(204, 204, 255));
        JLabel_Subtitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JLabel_Subtitle.setText("Edit general settings for the simulation");

        JLabel_Important.setBackground(new java.awt.Color(204, 204, 255));
        JLabel_Important.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JLabel_Important.setForeground(new java.awt.Color(255, 102, 0));
        JLabel_Important.setText("Important!");

        JLabel_ImportantMessage1.setBackground(new java.awt.Color(204, 204, 255));
        JLabel_ImportantMessage1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JLabel_ImportantMessage1.setText("To export changes or additions made to the network, go to \"Edit Network\"");

        JLabel_ImportantMessage2.setBackground(new java.awt.Color(204, 204, 255));
        JLabel_ImportantMessage2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JLabel_ImportantMessage2.setText("and select the \"Export Network\" option.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLabel_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLabel_Subtitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLabel_Important, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLabel_ImportantMessage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLabel_ImportantMessage2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(JLabel_Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLabel_Subtitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JLabel_Important)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLabel_ImportantMessage1)
                .addComponent(JLabel_ImportantMessage2)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        JLabel_ProjectName.setBackground(new java.awt.Color(204, 204, 255));
        JLabel_ProjectName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JLabel_ProjectName.setText("Project Name");

        JTextField_ProjectName.setBackground(new java.awt.Color(69, 71, 95));
        JTextField_ProjectName.setForeground(new java.awt.Color(255, 255, 255));
        JTextField_ProjectName.setText("newProject");

        JLabel_NetworkSourceFile.setBackground(new java.awt.Color(204, 204, 255));
        JLabel_NetworkSourceFile.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JLabel_NetworkSourceFile.setText("Network source file");

        JTextField_NodeSourceFile.setBackground(new java.awt.Color(69, 71, 95));
        JTextField_NodeSourceFile.setForeground(new java.awt.Color(255, 255, 255));
        JTextField_NodeSourceFile.setText("networkNodes.xml");

        JLabel_LastUpdate.setBackground(new java.awt.Color(204, 204, 255));
        JLabel_LastUpdate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JLabel_LastUpdate.setText("Last update");

        JLabel_LastUpdateOutput.setBackground(new java.awt.Color(0, 0, 0));
        JLabel_LastUpdateOutput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JLabel_LastUpdateOutput.setText("0");

        JLabel_NetworkFileFormat.setBackground(new java.awt.Color(204, 204, 255));
        JLabel_NetworkFileFormat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JLabel_NetworkFileFormat.setText("Network file format");

        JComboBox_NodeFileFormat.setBackground(new java.awt.Color(69, 71, 95));
        JComboBox_NodeFileFormat.setForeground(new java.awt.Color(255, 255, 255));
        JComboBox_NodeFileFormat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "default", "xml", "SQL (not implemented)" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JTextField_ProjectName)
                    .addComponent(JTextField_NodeSourceFile)
                    .addComponent(JLabel_NetworkSourceFile, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(JLabel_ProjectName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JLabel_LastUpdateOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLabel_NetworkFileFormat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLabel_LastUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JComboBox_NodeFileFormat, 0, 238, Short.MAX_VALUE))
                .addGap(44, 44, 44))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabel_LastUpdate)
                    .addComponent(JLabel_ProjectName))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabel_LastUpdateOutput)
                    .addComponent(JTextField_ProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabel_NetworkSourceFile)
                    .addComponent(JLabel_NetworkFileFormat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTextField_NodeSourceFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JComboBox_NodeFileFormat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        JLabel_TickNumber.setBackground(new java.awt.Color(204, 204, 255));
        JLabel_TickNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JLabel_TickNumber.setText("Number of ticks");

        JTextField_TickNumber.setBackground(new java.awt.Color(69, 71, 95));
        JTextField_TickNumber.setForeground(new java.awt.Color(255, 255, 255));
        JTextField_TickNumber.setText("1000");
        JTextField_TickNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTextField_TickNumberKeyTyped(evt);
            }
        });

        JLabel_SampleNumber.setBackground(new java.awt.Color(204, 204, 255));
        JLabel_SampleNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JLabel_SampleNumber.setText("Number of samples");

        JTextField_SampleNumber.setBackground(new java.awt.Color(69, 71, 95));
        JTextField_SampleNumber.setForeground(new java.awt.Color(255, 255, 255));
        JTextField_SampleNumber.setText("30");
        JTextField_SampleNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTextField_SampleNumberKeyTyped(evt);
            }
        });

        JLabel_NetworkNumber.setBackground(new java.awt.Color(204, 204, 255));
        JLabel_NetworkNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JLabel_NetworkNumber.setText("Number of networks");

        JTextField_NetworkNumber.setBackground(new java.awt.Color(69, 71, 95));
        JTextField_NetworkNumber.setForeground(new java.awt.Color(255, 255, 255));
        JTextField_NetworkNumber.setText("10");
        JTextField_NetworkNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTextField_NetworkNumberKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(JTextField_SampleNumber, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLabel_TickNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JTextField_TickNumber, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLabel_SampleNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JTextField_NetworkNumber)
                    .addComponent(JLabel_NetworkNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(JLabel_TickNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTextField_TickNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(JLabel_NetworkNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTextField_NetworkNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLabel_SampleNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTextField_SampleNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        JButton_Export.setBackground(new java.awt.Color(126, 129, 161));
        JButton_Export.setForeground(new java.awt.Color(51, 51, 51));
        JButton_Export.setText("Export Configurations");
        JButton_Export.setBorderPainted(false);
        JButton_Export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_ExportActionPerformed(evt);
            }
        });

        JButton_Import.setBackground(new java.awt.Color(126, 129, 161));
        JButton_Import.setForeground(new java.awt.Color(51, 51, 51));
        JButton_Import.setText("Import Configurations");
        JButton_Import.setBorderPainted(false);
        JButton_Import.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_ImportActionPerformed(evt);
            }
        });

        JButton_Save.setBackground(new java.awt.Color(126, 129, 161));
        JButton_Save.setForeground(new java.awt.Color(51, 51, 51));
        JButton_Save.setText("Save");
        JButton_Save.setBorderPainted(false);
        JButton_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_SaveActionPerformed(evt);
            }
        });

        JButton_Reset.setBackground(new java.awt.Color(126, 129, 161));
        JButton_Reset.setForeground(new java.awt.Color(51, 51, 51));
        JButton_Reset.setText("Reset");
        JButton_Reset.setBorderPainted(false);
        JButton_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_ResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JButton_Export)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JButton_Import)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JButton_Save)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JButton_Reset)
                .addGap(38, 38, 38))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JButton_Reset)
                    .addComponent(JButton_Save)
                    .addComponent(JButton_Export)
                    .addComponent(JButton_Import))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelGeneralConfigurationsScreenLayout = new javax.swing.GroupLayout(jPanelGeneralConfigurationsScreen);
        jPanelGeneralConfigurationsScreen.setLayout(jPanelGeneralConfigurationsScreenLayout);
        jPanelGeneralConfigurationsScreenLayout.setHorizontalGroup(
            jPanelGeneralConfigurationsScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeneralConfigurationsScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelGeneralConfigurationsScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelGeneralConfigurationsScreenLayout.setVerticalGroup(
            jPanelGeneralConfigurationsScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeneralConfigurationsScreenLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanelGeneralConfigurationsScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(338, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelGeneralConfigurationsScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JTextField_TickNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTextField_TickNumberKeyTyped
                if (!fieldValidation.getNumCharAllowed().contains(evt.getKeyChar() + "")) {
                    evt.consume();
                }
    }//GEN-LAST:event_JTextField_TickNumberKeyTyped

    private void JTextField_NetworkNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTextField_NetworkNumberKeyTyped
                if (!fieldValidation.getNumCharAllowed().contains(evt.getKeyChar() + "")) {
                    evt.consume();
                }
    }//GEN-LAST:event_JTextField_NetworkNumberKeyTyped

    private void JTextField_SampleNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTextField_SampleNumberKeyTyped
                if (!fieldValidation.getNumCharAllowed().contains(evt.getKeyChar() + "")) {
                    evt.consume();
                }
    }//GEN-LAST:event_JTextField_SampleNumberKeyTyped

    private void JButton_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_ResetActionPerformed
                int dialogResult = JOptionPane.showConfirmDialog(null, "This action will restore the last saved settings. Do you want to proceed?", "Warning", JOptionPane.YES_NO_OPTION);
                if (dialogResult == JOptionPane.YES_OPTION) {
                    setComponents();
                }
    }//GEN-LAST:event_JButton_ResetActionPerformed

    private void JButton_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_SaveActionPerformed
        // Checks if all fields are filled
        if (JTextField_ProjectName.getText().length() == 0
                || JTextField_NodeSourceFile.getText().length() == 0
                || JTextField_TickNumber.getText().length() == 0
                || JTextField_NetworkNumber.getText().length() == 0
                || JTextField_SampleNumber.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "[ERROR] Please fill all fields.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Checks that numeric fields contain only numbers and are positive and greater than zero
        if (JTextField_TickNumber.getText().matches("[0-9]+") == false
                || Integer.valueOf(JTextField_TickNumber.getText()) <= 0
                || JTextField_NetworkNumber.getText().matches("[0-9]+") == false
                || Integer.valueOf(JTextField_NetworkNumber.getText()) <= 0
                || JTextField_SampleNumber.getText().matches("[0-9]+") == false
                || Integer.valueOf(JTextField_SampleNumber.getText()) <= 0) {
            JOptionPane.showMessageDialog(this, "[ERROR] The Number of Ticks, Networks or Samples fields must be a numeric and positive value.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        saveConfigurations();
    }//GEN-LAST:event_JButton_SaveActionPerformed

    private void JButton_ExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_ExportActionPerformed
        int dialogResult = JOptionPane.showConfirmDialog(null, "This action will save the current settings. Do you want to proceed?", "Warning", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
            saveConfigurations();
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
            int returnVal = fileChooser.showOpenDialog(this);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                File file = fileChooser.getSelectedFile();
                configurations.saveConfigs(file);
                JOptionPane.showMessageDialog(this, "File saved successfully.", "File Saved", JOptionPane.INFORMATION_MESSAGE);
            } else {
                System.out.println("File access cancelled by user.");
            }
        }
    }//GEN-LAST:event_JButton_ExportActionPerformed

    private void JButton_ImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_ImportActionPerformed
                int dialogResult = JOptionPane.showConfirmDialog(null, "This action will discard the current settings. Do you want to proceed?", "Warning", JOptionPane.YES_NO_OPTION);
                if (dialogResult == JOptionPane.YES_OPTION) {
                    JFileChooser fileChooser = new JFileChooser();
                    fileChooser.setDialogType(javax.swing.JFileChooser.OPEN_DIALOG);
                    int returnVal = fileChooser.showOpenDialog(this);
                    if (returnVal == JFileChooser.APPROVE_OPTION) {
                        File file = fileChooser.getSelectedFile();
                        configurations.loadConfigs(file);
                        setComponents();
                        JOptionPane.showMessageDialog(this, "File imported successfully.", "Successful Import", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        System.out.println("File access cancelled by user.");
                    }
                }
    }//GEN-LAST:event_JButton_ImportActionPerformed

    public void saveConfigurations() {
        configurations.projectName = JTextField_ProjectName.getText();
        configurations.lastUpdate = new Date();
        JLabel_LastUpdateOutput.setText(Config.dateFormat.format(configurations.lastUpdate));
        configurations.networkSourceFileName = JTextField_NodeSourceFile.getText();
        configurations.networkSourceInputType = JComboBox_NodeFileFormat.getSelectedItem().toString();
        configurations.numberOfTicks = Integer.valueOf(JTextField_TickNumber.getText());
        configurations.numberOfNetworks = Integer.valueOf(JTextField_NetworkNumber.getText());
        configurations.numberOfSamples = Integer.valueOf(JTextField_SampleNumber.getText());
        if (configurations.saveConfigs() == true) {
            JOptionPane.showMessageDialog(this, "Project settings saved successfully.", "Save Configurations", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "[ERROR] There was an error trying to save the project settings.", "Save Configurations", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButton_Export;
    private javax.swing.JButton JButton_Import;
    private javax.swing.JButton JButton_Reset;
    private javax.swing.JButton JButton_Save;
    private javax.swing.JComboBox<String> JComboBox_NodeFileFormat;
    private javax.swing.JLabel JLabel_Important;
    private javax.swing.JLabel JLabel_ImportantMessage1;
    private javax.swing.JLabel JLabel_ImportantMessage2;
    private javax.swing.JLabel JLabel_LastUpdate;
    private javax.swing.JLabel JLabel_LastUpdateOutput;
    private javax.swing.JLabel JLabel_NetworkFileFormat;
    private javax.swing.JLabel JLabel_NetworkNumber;
    private javax.swing.JLabel JLabel_NetworkSourceFile;
    private javax.swing.JLabel JLabel_ProjectName;
    private javax.swing.JLabel JLabel_SampleNumber;
    private javax.swing.JLabel JLabel_Subtitle;
    private javax.swing.JLabel JLabel_TickNumber;
    private javax.swing.JLabel JLabel_Title;
    private javax.swing.JTextField JTextField_NetworkNumber;
    private javax.swing.JTextField JTextField_NodeSourceFile;
    private javax.swing.JTextField JTextField_ProjectName;
    private javax.swing.JTextField JTextField_SampleNumber;
    private javax.swing.JTextField JTextField_TickNumber;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelGeneralConfigurationsScreen;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
