/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.pseudocell.gui.tests;

/**
 *
 * @author ViníciusPierdoná
 */
public class TesteTabs extends javax.swing.JFrame {

    /**
     * Creates new form TesteTabs
     */
    public TesteTabs() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane_Menu = new javax.swing.JTabbedPane();
        jPanel_NewProject = new javax.swing.JPanel();
        jPanel_GeneralConfiguration = new javax.swing.JPanel();
        jPanel_NodeConfiguartion = new javax.swing.JPanel();
        jPanel_RulesConfiguration = new javax.swing.JPanel();
        jPanel_NetworkStimulation = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1200, 680));
        setMinimumSize(new java.awt.Dimension(1200, 680));

        jTabbedPane_Menu.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane_Menu.setMaximumSize(new java.awt.Dimension(1200, 680));
        jTabbedPane_Menu.setMinimumSize(new java.awt.Dimension(148, 100));

        javax.swing.GroupLayout jPanel_NewProjectLayout = new javax.swing.GroupLayout(jPanel_NewProject);
        jPanel_NewProject.setLayout(jPanel_NewProjectLayout);
        jPanel_NewProjectLayout.setHorizontalGroup(
            jPanel_NewProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1152, Short.MAX_VALUE)
        );
        jPanel_NewProjectLayout.setVerticalGroup(
            jPanel_NewProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );

        jTabbedPane_Menu.addTab("tab1", jPanel_NewProject);

        javax.swing.GroupLayout jPanel_GeneralConfigurationLayout = new javax.swing.GroupLayout(jPanel_GeneralConfiguration);
        jPanel_GeneralConfiguration.setLayout(jPanel_GeneralConfigurationLayout);
        jPanel_GeneralConfigurationLayout.setHorizontalGroup(
            jPanel_GeneralConfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1152, Short.MAX_VALUE)
        );
        jPanel_GeneralConfigurationLayout.setVerticalGroup(
            jPanel_GeneralConfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );

        jTabbedPane_Menu.addTab("tab2", jPanel_GeneralConfiguration);

        javax.swing.GroupLayout jPanel_NodeConfiguartionLayout = new javax.swing.GroupLayout(jPanel_NodeConfiguartion);
        jPanel_NodeConfiguartion.setLayout(jPanel_NodeConfiguartionLayout);
        jPanel_NodeConfiguartionLayout.setHorizontalGroup(
            jPanel_NodeConfiguartionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1152, Short.MAX_VALUE)
        );
        jPanel_NodeConfiguartionLayout.setVerticalGroup(
            jPanel_NodeConfiguartionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );

        jTabbedPane_Menu.addTab("tab3", jPanel_NodeConfiguartion);

        javax.swing.GroupLayout jPanel_RulesConfigurationLayout = new javax.swing.GroupLayout(jPanel_RulesConfiguration);
        jPanel_RulesConfiguration.setLayout(jPanel_RulesConfigurationLayout);
        jPanel_RulesConfigurationLayout.setHorizontalGroup(
            jPanel_RulesConfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1152, Short.MAX_VALUE)
        );
        jPanel_RulesConfigurationLayout.setVerticalGroup(
            jPanel_RulesConfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );

        jTabbedPane_Menu.addTab("tab4", jPanel_RulesConfiguration);

        javax.swing.GroupLayout jPanel_NetworkStimulationLayout = new javax.swing.GroupLayout(jPanel_NetworkStimulation);
        jPanel_NetworkStimulation.setLayout(jPanel_NetworkStimulationLayout);
        jPanel_NetworkStimulationLayout.setHorizontalGroup(
            jPanel_NetworkStimulationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1152, Short.MAX_VALUE)
        );
        jPanel_NetworkStimulationLayout.setVerticalGroup(
            jPanel_NetworkStimulationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );

        jTabbedPane_Menu.addTab("tab5", jPanel_NetworkStimulation);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane_Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane_Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TesteTabs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TesteTabs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TesteTabs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TesteTabs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TesteTabs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel_GeneralConfiguration;
    private javax.swing.JPanel jPanel_NetworkStimulation;
    private javax.swing.JPanel jPanel_NewProject;
    private javax.swing.JPanel jPanel_NodeConfiguartion;
    private javax.swing.JPanel jPanel_RulesConfiguration;
    private javax.swing.JTabbedPane jTabbedPane_Menu;
    // End of variables declaration//GEN-END:variables
}
