/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.pseudocell.gui.cards;

import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import org.pseudocell.core.Pseudocell;
import org.pseudocell.core.PseudocellFactory;
import org.pseudocell.core.nodes.Node;
import org.pseudocell.config.Config;
import org.pseudocell.config.ConfigNodeStimulation;
import org.pseudocell.gui.validation.FieldValidation;

/**
 *
 * @author ViníciusPierdoná
 */
public class NewProject extends javax.swing.JPanel {

    Config configurations;
    ConfigNodeStimulation configNodeStimulation;
    List<Node> nodeList;
    FieldValidation fieldValidation;
    // Variable responsible for stopping code execution if the user presses the cancel button.
    boolean cancel;

    /**
     * Creates new form NewProject
     *
     * @param configurations
     * @param nodeList
     */
    public NewProject(Config configurations, ConfigNodeStimulation configNodeStimulation, List<Node> nodeList) {
        initComponents();

        fieldValidation = new FieldValidation();
        this.configurations = configurations;
        this.configNodeStimulation = configNodeStimulation;
        this.nodeList = nodeList;

        // Create a listener to control the methods needed when shown or hidden the card
        addComponentListener(new ComponentAdapter() {
            @Override
            public void componentHidden(ComponentEvent evt) {
                hidden();
            }

            @Override
            public void componentShown(ComponentEvent evt) {
                shown();
            }
        });
    }

    public void shown() {
        setComponents();
    }

    public void hidden() {

    }

    private void setComponents() {
        jTextFieldNPProjectName.setText(configurations.projectName);
        jLabelNPNetworkSizeOutput.setText(String.valueOf(nodeList.size()));
        jLabelNPNumberNetworksOutput.setText(String.valueOf(configurations.numberOfNetworks));
        jLabelNPNumberOfTicksOutput.setText(String.valueOf(configurations.numberOfTicks));
        jButtonNPCancel.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelNewProjectScreen = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelNPTitle = new javax.swing.JLabel();
        jTextFieldNPProjectName = new javax.swing.JTextField();
        jLabelNPProjectName = new javax.swing.JLabel();
        jLabelNPNetworkSize = new javax.swing.JLabel();
        jLabelNPNumberNetworks = new javax.swing.JLabel();
        jLabelNPNetworkSizeOutput = new javax.swing.JLabel();
        jLabelNPNumberNetworksOutput = new javax.swing.JLabel();
        jLabelNPNumberOfTicks = new javax.swing.JLabel();
        jLabelNPNumberOfTicksOutput = new javax.swing.JLabel();
        jLabelNPSubtitle = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        listLogs = new java.awt.List();
        jLabelNPSimulationOutput = new javax.swing.JLabel();
        jButtonNPExecute = new javax.swing.JButton();
        jButtonNPCancel = new javax.swing.JButton();

        setBackground(new java.awt.Color(56, 58, 77));
        setMaximumSize(new java.awt.Dimension(900, 640));
        setMinimumSize(new java.awt.Dimension(900, 640));
        setPreferredSize(new java.awt.Dimension(900, 640));

        jPanelNewProjectScreen.setMaximumSize(new java.awt.Dimension(900, 640));
        jPanelNewProjectScreen.setMinimumSize(new java.awt.Dimension(900, 640));
        jPanelNewProjectScreen.setPreferredSize(new java.awt.Dimension(900, 640));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabelNPTitle.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelNPTitle.setText("Project Overview");

        jTextFieldNPProjectName.setBackground(new java.awt.Color(69, 71, 95));
        jTextFieldNPProjectName.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldNPProjectName.setText("newProject");
        jTextFieldNPProjectName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNPProjectNameActionPerformed(evt);
            }
        });

        jLabelNPProjectName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNPProjectName.setText("Project Name:");

        jLabelNPNetworkSize.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNPNetworkSize.setText("Network Size:");

        jLabelNPNumberNetworks.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNPNumberNetworks.setText("Number of Networks:");

        jLabelNPNetworkSizeOutput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNPNetworkSizeOutput.setText("0");

        jLabelNPNumberNetworksOutput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNPNumberNetworksOutput.setText("0");

        jLabelNPNumberOfTicks.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNPNumberOfTicks.setText("Number of Ticks:");

        jLabelNPNumberOfTicksOutput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNPNumberOfTicksOutput.setText("0");

        jLabelNPSubtitle.setBackground(new java.awt.Color(204, 204, 255));
        jLabelNPSubtitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNPSubtitle.setText("Create and execute a new PseudoCell simulation");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNPSubtitle)
                            .addComponent(jLabelNPTitle))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelNPProjectName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldNPProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 24, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelNPNumberOfTicks)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelNPNumberOfTicksOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelNPNumberNetworks)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelNPNumberNetworksOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelNPNetworkSize)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelNPNetworkSizeOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabelNPTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNPSubtitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNPProjectName)
                    .addComponent(jTextFieldNPProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNPNetworkSize)
                    .addComponent(jLabelNPNetworkSizeOutput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNPNumberNetworks)
                    .addComponent(jLabelNPNumberNetworksOutput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNPNumberOfTicks)
                    .addComponent(jLabelNPNumberOfTicksOutput))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));

        listLogs.setBackground(new java.awt.Color(69, 71, 95));
        listLogs.setForeground(new java.awt.Color(255, 255, 255));

        jLabelNPSimulationOutput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNPSimulationOutput.setText("Simulation Output");

        jButtonNPExecute.setBackground(new java.awt.Color(126, 129, 161));
        jButtonNPExecute.setForeground(new java.awt.Color(51, 51, 51));
        jButtonNPExecute.setText("Execute");
        jButtonNPExecute.setBorderPainted(false);
        jButtonNPExecute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNPExecuteActionPerformed(evt);
            }
        });

        jButtonNPCancel.setBackground(new java.awt.Color(126, 129, 161));
        jButtonNPCancel.setForeground(new java.awt.Color(51, 51, 51));
        jButtonNPCancel.setText("Cancel");
        jButtonNPCancel.setBorderPainted(false);
        jButtonNPCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNPCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(348, Short.MAX_VALUE)
                .addComponent(jButtonNPExecute)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonNPCancel)
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNPSimulationOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(listLogs, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(28, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabelNPSimulationOutput)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 318, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNPCancel)
                    .addComponent(jButtonNPExecute))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addComponent(listLogs, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(34, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanelNewProjectScreenLayout = new javax.swing.GroupLayout(jPanelNewProjectScreen);
        jPanelNewProjectScreen.setLayout(jPanelNewProjectScreenLayout);
        jPanelNewProjectScreenLayout.setHorizontalGroup(
            jPanelNewProjectScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNewProjectScreenLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanelNewProjectScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 347, Short.MAX_VALUE))
        );
        jPanelNewProjectScreenLayout.setVerticalGroup(
            jPanelNewProjectScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNewProjectScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelNewProjectScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelNewProjectScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNPExecuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNPExecuteActionPerformed
        // Checks if a name has been defined for the project
        if (jTextFieldNPProjectName.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "[ERROR] It is necessary to define a name for the project.", "Error - Empty field", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Checks that the Project Name field does not have more characters than the maximum allowed
        if (jTextFieldNPProjectName.getText().length() > fieldValidation.getMaxCharacterAllowed()) {
            JOptionPane.showMessageDialog(this, "[ERROR] Project Name cannot be longer than " + fieldValidation.getMaxCharacterAllowed() + " characters", "Error - Field out of bounds", JOptionPane.ERROR_MESSAGE);
            return;
        }

        listLogs.removeAll();
        jButtonNPCancel.setEnabled(true);
        jButtonNPExecute.setEnabled(false);
        cancel = false;

        listLogs.add(Config.dateFormat.format(new Date()) + " Loading settings:");
        listLogs.add("    Last update: " + Config.dateFormat.format(configurations.lastUpdate));
        listLogs.add("    Network Source Input Type: " + configurations.networkSourceInputType);
        listLogs.add("    Network Source Input File Name: " + configurations.networkSourceFileName);
        listLogs.add("    Number Of Networks: " + configurations.numberOfNetworks);
        listLogs.add("    Number Of Ticks: " + configurations.numberOfTicks);
        listLogs.add("    Node Stimulated: " + configNodeStimulation.stimulatedNode);
        listLogs.add("    Frequency of Stimulation: " + configNodeStimulation.stimulatedNodeFrequency);
        listLogs.add("   ");

        // Initialization of output file and destination directories
        String date = String.valueOf(LocalDate.now());
        String time = String.valueOf(LocalTime.now()).replace(":", "-");
        listLogs.add(Config.dateFormat.format(new Date()) + "    Creating directory " + "results/" + jTextFieldNPProjectName.getText() + "/" + date + "/" + time);
        new File("results/" + jTextFieldNPProjectName.getText() + "/" + date + "/" + time).mkdirs();
        listLogs.add(Config.dateFormat.format(new Date()) + "    Creating destiny file... ");
        listLogs.add(" ");

        // String responsible for receiving the activation frequencies of the nodes for each sample
        StringBuilder freq = new StringBuilder();
        try ( PrintWriter writer = new PrintWriter("results/" + jTextFieldNPProjectName.getText() + "/" + date + "/" + time + "/Frequency.csv")) {

            // Initialize the output file header
            freq.append("Sample");
            freq.append(',');
            // Populate the header of the output file with the name of the nodes
            for (Node node : nodeList) {
                freq.append(node.getName());
                freq.append(',');
            }
            freq.append('\n');

            listLogs.add(Config.dateFormat.format(new Date()) + " Starting experiments...");
            listLogs.add(" ");

            // Initialize loop through samples
            for (int j = 0; j < configurations.numberOfSamples; j++) {
                listLogs.add(" ");
                listLogs.add(Config.dateFormat.format(new Date()) + " Starting sample: " + j);
                listLogs.add(" ");
                // Initialize pseudoCell
                Pseudocell pseudocell = new PseudocellFactory().createPseudocell(configurations);
                // Initialize loop through ticks
                for (int i = 0; i < configurations.numberOfTicks; i++) {
                    if (!cancel) {
                        pseudocell.update();
                        listLogs.add(Config.dateFormat.format(new Date()) + " [info] " + Config.dateFormat.format(new Date()) + " Tick ended: " + i);
                    } else {
                        cancel = false;
                        return;
                    }
                }
                freq.append("Sample " + j + ",");
                for (Double nodeMeanFreq : pseudocell.getMeanExpression()) {
                    freq.append(nodeMeanFreq);
                    freq.append(",");
                }
                freq.append("\n");
            }
            writer.write(freq.toString());

        } catch (FileNotFoundException e) {
            System.out.println(e.getMessage());
        } catch (Exception ex) {
        }

        listLogs.add(" ");
        listLogs.add(Config.dateFormat.format(new Date()) + " Ending experiments...");
        listLogs.add(" ");
        jButtonNPExecute.setEnabled(true);
        jButtonNPCancel.setEnabled(false);
    }//GEN-LAST:event_jButtonNPExecuteActionPerformed

    private void jButtonNPCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNPCancelActionPerformed
        synchronized (this) {
            cancel = true;
        }
    }//GEN-LAST:event_jButtonNPCancelActionPerformed

    private void jTextFieldNPProjectNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNPProjectNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNPProjectNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNPCancel;
    private javax.swing.JButton jButtonNPExecute;
    private javax.swing.JLabel jLabelNPNetworkSize;
    private javax.swing.JLabel jLabelNPNetworkSizeOutput;
    private javax.swing.JLabel jLabelNPNumberNetworks;
    private javax.swing.JLabel jLabelNPNumberNetworksOutput;
    private javax.swing.JLabel jLabelNPNumberOfTicks;
    private javax.swing.JLabel jLabelNPNumberOfTicksOutput;
    private javax.swing.JLabel jLabelNPProjectName;
    private javax.swing.JLabel jLabelNPSimulationOutput;
    private javax.swing.JLabel jLabelNPSubtitle;
    private javax.swing.JLabel jLabelNPTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelNewProjectScreen;
    private javax.swing.JTextField jTextFieldNPProjectName;
    private java.awt.List listLogs;
    // End of variables declaration//GEN-END:variables
}
