/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.pseudocell.gui.cards;

/**
 *
 * @author ViníciusPierdoná
 */
public class NodeStimulation extends javax.swing.JPanel {

    /**
     * Creates new form NodeStimulation
     */
    public NodeStimulation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelNodeStimulationScreen = new javax.swing.JPanel();
        jLabelNPTitle1 = new javax.swing.JLabel();
        jLabelNPSubtitle1 = new javax.swing.JLabel();
        jLabelNSTargetNode = new javax.swing.JLabel();
        listNSNodesList = new java.awt.List();
        jTextFieldNSFilter = new javax.swing.JTextField();
        jLabelNSFilter = new javax.swing.JLabel();
        jButtonNSFilter = new javax.swing.JButton();
        jLabelNSNodeList = new javax.swing.JLabel();
        jButtonNSReset = new javax.swing.JButton();
        jButtonNSSave = new javax.swing.JButton();
        jTextFieldNSTargetNode = new javax.swing.JTextField();
        jLabelNSFrequency = new javax.swing.JLabel();
        jSliderNSFrequency = new javax.swing.JSlider();
        jLabelNSFrequencyOutput = new javax.swing.JLabel();
        jButtonNSExport = new javax.swing.JButton();
        jButtonNSImport = new javax.swing.JButton();

        jPanelNodeStimulationScreen.setBackground(new java.awt.Color(56, 58, 77));

        jLabelNPTitle1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelNPTitle1.setForeground(new java.awt.Color(204, 204, 255));
        jLabelNPTitle1.setText("Node Stimulation");

        jLabelNPSubtitle1.setBackground(new java.awt.Color(204, 204, 255));
        jLabelNPSubtitle1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNPSubtitle1.setForeground(new java.awt.Color(204, 204, 255));
        jLabelNPSubtitle1.setText("Create disturbances in the network and set how often nodes will be activated.");

        jLabelNSTargetNode.setBackground(new java.awt.Color(204, 204, 255));
        jLabelNSTargetNode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNSTargetNode.setForeground(new java.awt.Color(204, 204, 255));
        jLabelNSTargetNode.setText("Target Node");

        listNSNodesList.setBackground(new java.awt.Color(69, 71, 95));
        listNSNodesList.setForeground(new java.awt.Color(255, 255, 255));
        listNSNodesList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listNSNodesListMouseClicked(evt);
            }
        });

        jTextFieldNSFilter.setBackground(new java.awt.Color(69, 71, 95));
        jTextFieldNSFilter.setForeground(new java.awt.Color(255, 255, 255));

        jLabelNSFilter.setBackground(new java.awt.Color(204, 204, 255));
        jLabelNSFilter.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNSFilter.setForeground(new java.awt.Color(204, 204, 255));
        jLabelNSFilter.setText("Filter");

        jButtonNSFilter.setBackground(new java.awt.Color(126, 129, 161));
        jButtonNSFilter.setForeground(new java.awt.Color(51, 51, 51));
        jButtonNSFilter.setText("Filter");
        jButtonNSFilter.setBorderPainted(false);
        jButtonNSFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNSFilterActionPerformed(evt);
            }
        });

        jLabelNSNodeList.setBackground(new java.awt.Color(204, 204, 255));
        jLabelNSNodeList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNSNodeList.setForeground(new java.awt.Color(204, 204, 255));
        jLabelNSNodeList.setText("Node List");

        jButtonNSReset.setBackground(new java.awt.Color(126, 129, 161));
        jButtonNSReset.setForeground(new java.awt.Color(51, 51, 51));
        jButtonNSReset.setText("Reset");
        jButtonNSReset.setBorderPainted(false);
        jButtonNSReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNSResetActionPerformed(evt);
            }
        });

        jButtonNSSave.setBackground(new java.awt.Color(126, 129, 161));
        jButtonNSSave.setForeground(new java.awt.Color(51, 51, 51));
        jButtonNSSave.setText("Save");
        jButtonNSSave.setBorderPainted(false);
        jButtonNSSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNSSaveActionPerformed(evt);
            }
        });

        jTextFieldNSTargetNode.setBackground(new java.awt.Color(69, 71, 95));
        jTextFieldNSTargetNode.setForeground(new java.awt.Color(255, 255, 255));

        jLabelNSFrequency.setBackground(new java.awt.Color(204, 204, 255));
        jLabelNSFrequency.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNSFrequency.setForeground(new java.awt.Color(204, 204, 255));
        jLabelNSFrequency.setText("Frequency of stimulation:");

        jSliderNSFrequency.setBackground(new java.awt.Color(69, 71, 95));
        jSliderNSFrequency.setMajorTickSpacing(1);
        jSliderNSFrequency.setMinimum(1);
        jSliderNSFrequency.setMinorTickSpacing(1);
        jSliderNSFrequency.setValue(10);
        jSliderNSFrequency.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderNSFrequencyStateChanged(evt);
            }
        });

        jLabelNSFrequencyOutput.setBackground(new java.awt.Color(204, 204, 255));
        jLabelNSFrequencyOutput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNSFrequencyOutput.setForeground(new java.awt.Color(204, 204, 255));
        jLabelNSFrequencyOutput.setText("0");

        jButtonNSExport.setBackground(new java.awt.Color(126, 129, 161));
        jButtonNSExport.setForeground(new java.awt.Color(51, 51, 51));
        jButtonNSExport.setText("Export Configurations");
        jButtonNSExport.setBorderPainted(false);
        jButtonNSExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNSExportActionPerformed(evt);
            }
        });

        jButtonNSImport.setBackground(new java.awt.Color(126, 129, 161));
        jButtonNSImport.setForeground(new java.awt.Color(51, 51, 51));
        jButtonNSImport.setText("Import Configurations");
        jButtonNSImport.setBorderPainted(false);
        jButtonNSImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNSImportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelNodeStimulationScreenLayout = new javax.swing.GroupLayout(jPanelNodeStimulationScreen);
        jPanelNodeStimulationScreen.setLayout(jPanelNodeStimulationScreenLayout);
        jPanelNodeStimulationScreenLayout.setHorizontalGroup(
            jPanelNodeStimulationScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNodeStimulationScreenLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanelNodeStimulationScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelNodeStimulationScreenLayout.createSequentialGroup()
                        .addComponent(jButtonNSExport)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonNSImport)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonNSSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonNSReset)
                        .addGap(40, 40, 40))
                    .addGroup(jPanelNodeStimulationScreenLayout.createSequentialGroup()
                        .addGroup(jPanelNodeStimulationScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNPSubtitle1)
                            .addComponent(jLabelNPTitle1)
                            .addComponent(jLabelNSFilter))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelNodeStimulationScreenLayout.createSequentialGroup()
                        .addGroup(jPanelNodeStimulationScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelNSNodeList, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelNodeStimulationScreenLayout.createSequentialGroup()
                                .addComponent(jTextFieldNSFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonNSFilter))
                            .addComponent(listNSNodesList, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelNodeStimulationScreenLayout.createSequentialGroup()
                                .addGroup(jPanelNodeStimulationScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNSTargetNode)
                                    .addComponent(jTextFieldNSTargetNode, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(88, 88, 88)
                                .addGroup(jPanelNodeStimulationScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSliderNSFrequency, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanelNodeStimulationScreenLayout.createSequentialGroup()
                                        .addComponent(jLabelNSFrequency)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelNSFrequencyOutput)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(0, 70, Short.MAX_VALUE))))
        );
        jPanelNodeStimulationScreenLayout.setVerticalGroup(
            jPanelNodeStimulationScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNodeStimulationScreenLayout.createSequentialGroup()
                .addGroup(jPanelNodeStimulationScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelNodeStimulationScreenLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabelNPTitle1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelNPSubtitle1))
                    .addGroup(jPanelNodeStimulationScreenLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabelNSFilter)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelNodeStimulationScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNSFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNSFilter))
                .addGap(21, 21, 21)
                .addComponent(jLabelNSNodeList)
                .addGap(2, 2, 2)
                .addComponent(listNSNodesList, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelNodeStimulationScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNSTargetNode)
                    .addComponent(jLabelNSFrequency)
                    .addComponent(jLabelNSFrequencyOutput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelNodeStimulationScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelNodeStimulationScreenLayout.createSequentialGroup()
                        .addComponent(jSliderNSFrequency, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(117, 117, 117))
                    .addGroup(jPanelNodeStimulationScreenLayout.createSequentialGroup()
                        .addComponent(jTextFieldNSTargetNode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelNodeStimulationScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonNSExport)
                            .addComponent(jButtonNSImport)
                            .addComponent(jButtonNSSave)
                            .addComponent(jButtonNSReset))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelNodeStimulationScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 687, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelNodeStimulationScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void listNSNodesListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listNSNodesListMouseClicked
        Node selectedNode = nodesDisplayed.get(listNSNodesList.getSelectedIndex());
        jTextFieldNSTargetNode.setText(selectedNode.getName());
    }//GEN-LAST:event_listNSNodesListMouseClicked

    private void jButtonNSFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNSFilterActionPerformed
        listNSNodesList.removeAll();
        filterNodes(jTextFieldNSFilter.getText(), listNSNodesList);
    }//GEN-LAST:event_jButtonNSFilterActionPerformed

    private void jButtonNSResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNSResetActionPerformed
        int dialogResult = JOptionPane.showConfirmDialog (null, "This action will remove the current stimulus. Are you sure you want to proceed?","Warning",JOptionPane.YES_NO_OPTION);
        if(dialogResult == JOptionPane.YES_OPTION){
            configNodeStimulation.stimulatedNode = "";
            configNodeStimulation.stimulatedNodeFrequency = 10;
            jTextFieldNSTargetNode.setText(configNodeStimulation.stimulatedNode);
            jLabelNSFrequencyOutput.setText(String.valueOf(configNodeStimulation.stimulatedNodeFrequency));
            jSliderNSFrequency.setValue(configNodeStimulation.stimulatedNodeFrequency);
        }
    }//GEN-LAST:event_jButtonNSResetActionPerformed

    private void jButtonNSSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNSSaveActionPerformed
        if (jTextFieldNSTargetNode.getText() == null || jTextFieldNSTargetNode.getText() == "") {
            configNodeStimulation.stimulatedNode = "";
        } else {
            configNodeStimulation.stimulatedNode = jTextFieldNSTargetNode.getText();
        }
        configNodeStimulation.stimulatedNodeFrequency = jSliderNSFrequency.getValue();
        if (configNodeStimulation.saveConfigs() == true) {
            JOptionPane.showMessageDialog(rootPane, "Node stimulation settings saved successfully.", "Save Configurations", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(rootPane, "[ERROR] There was an error trying to save the node stimulation settings.", "Save Configurations", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonNSSaveActionPerformed

    private void jSliderNSFrequencyStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderNSFrequencyStateChanged
        jLabelNSFrequencyOutput.setText(String.valueOf(jSliderNSFrequency.getValue()));
        setVisible(true);
    }//GEN-LAST:event_jSliderNSFrequencyStateChanged

    private void jButtonNSExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNSExportActionPerformed
        if (jTextFieldNSTargetNode.getText() == null || jTextFieldNSTargetNode.getText() == "") {
            configNodeStimulation.stimulatedNode = "";
        } else {
            configNodeStimulation.stimulatedNode = jTextFieldNSTargetNode.getText();
        }
        configNodeStimulation.stimulatedNodeFrequency = jSliderNSFrequency.getValue();
        if (configNodeStimulation.saveConfigs() == true) {
            JOptionPane.showMessageDialog(rootPane, "Node stimulation settings saved successfully.", "Save Configurations", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(rootPane, "[ERROR] There was an error trying to save the node stimulation settings.", "Save Configurations", JOptionPane.ERROR_MESSAGE);
        }
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile() ;
            configNodeStimulation.saveConfigs(file);
            JOptionPane.showMessageDialog(rootPane, "File saved successfully.","File Saved", JOptionPane.INFORMATION_MESSAGE);
        } else {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_jButtonNSExportActionPerformed

    private void jButtonNSImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNSImportActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogType(javax.swing.JFileChooser.OPEN_DIALOG);
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            configNodeStimulation.loadConfigs(file);
            initNSComponents();
            JOptionPane.showMessageDialog(rootPane, "File imported successfully.","Successful Import", JOptionPane.INFORMATION_MESSAGE);
        } else {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_jButtonNSImportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNSExport;
    private javax.swing.JButton jButtonNSFilter;
    private javax.swing.JButton jButtonNSImport;
    private javax.swing.JButton jButtonNSReset;
    private javax.swing.JButton jButtonNSSave;
    private javax.swing.JLabel jLabelNPSubtitle1;
    private javax.swing.JLabel jLabelNPTitle1;
    private javax.swing.JLabel jLabelNSFilter;
    private javax.swing.JLabel jLabelNSFrequency;
    private javax.swing.JLabel jLabelNSFrequencyOutput;
    private javax.swing.JLabel jLabelNSNodeList;
    private javax.swing.JLabel jLabelNSTargetNode;
    private javax.swing.JPanel jPanelNodeStimulationScreen;
    private javax.swing.JSlider jSliderNSFrequency;
    private javax.swing.JTextField jTextFieldNSFilter;
    private javax.swing.JTextField jTextFieldNSTargetNode;
    private java.awt.List listNSNodesList;
    // End of variables declaration//GEN-END:variables
}
