/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.pseudocell.gui.cards;

import java.awt.Color;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.io.File;
import java.io.IOException;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.TransformerException;
import org.pseudocell.core.NetworkFactory;
import org.pseudocell.core.nodes.Metabolite;
import org.pseudocell.core.nodes.Node;
import org.pseudocell.core.persistence.XMLNetworkReader;
import org.pseudocell.core.persistence.XMLNetworkWriter;
import org.pseudocell.config.Config;
import org.pseudocell.gui.nodes.CreateKnockout;
import org.pseudocell.gui.nodes.CreateModification;
import org.pseudocell.gui.nodes.EditModification;
import org.pseudocell.gui.utils.NodeFilter;
import org.xml.sax.SAXException;

/**
 *
 * @author ViníciusPierdoná
 */
public class NodeConfigurations extends javax.swing.JPanel {

    private static final int TYPE_PROTEINGENE = 1;
    private static final int TYPE_METABOLITE = 2;
    private static final int TYPE_OTHER = 3;
    private static final int TYPE_MIRNA = 4;
    private static final int TYPE_DRUG = 5;

    NetworkFactory networkFactory;
    Config configurations;
    List<Node> nodeList, displayedNodes;
    NodeFilter nodeFilter;
    Node selectedNode;

    Color colorBlock;
    Color colorEnabled;

    /**
     * Creates new form NodeConfigurations
     *
     * @param configurations
     * @param nodeList
     */
    public NodeConfigurations(Config configurations, List<Node> nodeList) {
        initComponents();

        this.configurations = configurations;
        this.nodeList = nodeList;
        this.networkFactory = new NetworkFactory();
        this.nodeFilter = new NodeFilter();

        colorBlock = new Color(53, 55, 71);
        colorEnabled = new Color(69, 71, 95);

        // Create a listener to control the methods needed when shown or hidden the card
        addComponentListener(new ComponentAdapter() {
            @Override
            public void componentHidden(ComponentEvent evt) {
                hidden();
            }

            @Override
            public void componentShown(ComponentEvent evt) {
                shown();
            }
        });
    }

    public void hidden() {

    }

    public void shown() {
        setComponents();
    }

    public void setComponents() {
        displayedNodes = nodeFilter.filterNodes(listNodesList, nodeList, null);
        jTextFieldName.setEditable(false);
        jTextFieldType.setEditable(false);
        jTextFieldName.setBackground(colorBlock);
        jTextFieldType.setBackground(colorBlock);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabelNCFilter2 = new javax.swing.JLabel();
        jLabelNCFilter5 = new javax.swing.JLabel();
        jPanelNodeConfigurationsScreen = new javax.swing.JPanel();
        jLabelTitle1 = new javax.swing.JLabel();
        jLabelSubtitle = new javax.swing.JLabel();
        jLabelFilter = new javax.swing.JLabel();
        jTextFieldFilter = new javax.swing.JTextField();
        jButtonFilter = new javax.swing.JButton();
        jLabelNCNodesList = new javax.swing.JLabel();
        listNodesList = new java.awt.List();
        jButtonReset = new javax.swing.JButton();
        jButtonExportNodes = new javax.swing.JButton();
        jButtonImportNodes = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jLabelTitle2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelName = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabelStatus = new javax.swing.JLabel();
        jTextFieldStatus = new javax.swing.JTextField();
        jLabelRestingStatus = new javax.swing.JLabel();
        jTextFieldRestingStatus = new javax.swing.JTextField();
        jLabelModifications = new javax.swing.JLabel();
        jComboBoxModifications = new javax.swing.JComboBox<>();
        jButtonEditMod = new javax.swing.JButton();
        jButtonAddMod = new javax.swing.JButton();
        jLabelType = new javax.swing.JLabel();
        jLabelIncome = new javax.swing.JLabel();
        jTextFieldIncome = new javax.swing.JTextField();
        jLabelMinValue = new javax.swing.JLabel();
        jTextFieldMinValue = new javax.swing.JTextField();
        jLabelMaxValue = new javax.swing.JLabel();
        jTextFieldMaxValue = new javax.swing.JTextField();
        jButtonKnockout = new javax.swing.JButton();
        jButtonAddNode = new javax.swing.JButton();
        jTextFieldType = new javax.swing.JTextField();

        jLabelNCFilter2.setBackground(new java.awt.Color(204, 204, 255));
        jLabelNCFilter2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNCFilter2.setForeground(new java.awt.Color(204, 204, 255));
        jLabelNCFilter2.setText("Filter");

        jLabelNCFilter5.setBackground(new java.awt.Color(204, 204, 255));
        jLabelNCFilter5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNCFilter5.setForeground(new java.awt.Color(204, 204, 255));
        jLabelNCFilter5.setText("Filter");

        setMaximumSize(new java.awt.Dimension(650, 720));
        setPreferredSize(new java.awt.Dimension(650, 720));

        jPanelNodeConfigurationsScreen.setBackground(new java.awt.Color(56, 58, 77));
        jPanelNodeConfigurationsScreen.setMaximumSize(new java.awt.Dimension(650, 720));
        jPanelNodeConfigurationsScreen.setPreferredSize(new java.awt.Dimension(650, 720));
        jPanelNodeConfigurationsScreen.setLayout(new java.awt.GridBagLayout());

        jLabelTitle1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelTitle1.setForeground(new java.awt.Color(204, 204, 255));
        jLabelTitle1.setText("Node Configurations");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(43, 34, 0, 0);
        jPanelNodeConfigurationsScreen.add(jLabelTitle1, gridBagConstraints);

        jLabelSubtitle.setBackground(new java.awt.Color(204, 204, 255));
        jLabelSubtitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelSubtitle.setForeground(new java.awt.Color(204, 204, 255));
        jLabelSubtitle.setText("Edit key node settings such as their initial state or knockout specific nodes");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 53;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 34, 0, 0);
        jPanelNodeConfigurationsScreen.add(jLabelSubtitle, gridBagConstraints);

        jLabelFilter.setBackground(new java.awt.Color(204, 204, 255));
        jLabelFilter.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelFilter.setForeground(new java.awt.Color(204, 204, 255));
        jLabelFilter.setText("Filter");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(22, 34, 0, 0);
        jPanelNodeConfigurationsScreen.add(jLabelFilter, gridBagConstraints);

        jTextFieldFilter.setBackground(new java.awt.Color(69, 71, 95));
        jTextFieldFilter.setForeground(new java.awt.Color(255, 255, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 133;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 34, 0, 0);
        jPanelNodeConfigurationsScreen.add(jTextFieldFilter, gridBagConstraints);

        jButtonFilter.setBackground(new java.awt.Color(126, 129, 161));
        jButtonFilter.setForeground(new java.awt.Color(51, 51, 51));
        jButtonFilter.setText("Filter");
        jButtonFilter.setBorderPainted(false);
        jButtonFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFilterActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 0);
        jPanelNodeConfigurationsScreen.add(jButtonFilter, gridBagConstraints);

        jLabelNCNodesList.setBackground(new java.awt.Color(204, 204, 255));
        jLabelNCNodesList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNCNodesList.setForeground(new java.awt.Color(204, 204, 255));
        jLabelNCNodesList.setText("Nodes List");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 34, 0, 0);
        jPanelNodeConfigurationsScreen.add(jLabelNCNodesList, gridBagConstraints);

        listNodesList.setBackground(new java.awt.Color(69, 71, 95));
        listNodesList.setForeground(new java.awt.Color(255, 255, 255));
        listNodesList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listNodesListMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 157;
        gridBagConstraints.ipadx = 505;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 34, 0, 71);
        jPanelNodeConfigurationsScreen.add(listNodesList, gridBagConstraints);

        jButtonReset.setBackground(new java.awt.Color(126, 129, 161));
        jButtonReset.setForeground(new java.awt.Color(51, 51, 51));
        jButtonReset.setText("Reset Nodes");
        jButtonReset.setBorderPainted(false);
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 52;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.gridwidth = 105;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 98, 71);
        jPanelNodeConfigurationsScreen.add(jButtonReset, gridBagConstraints);

        jButtonExportNodes.setBackground(new java.awt.Color(126, 129, 161));
        jButtonExportNodes.setForeground(new java.awt.Color(51, 51, 51));
        jButtonExportNodes.setText("Export Nodes");
        jButtonExportNodes.setBorderPainted(false);
        jButtonExportNodes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExportNodesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 34, 98, 0);
        jPanelNodeConfigurationsScreen.add(jButtonExportNodes, gridBagConstraints);

        jButtonImportNodes.setBackground(new java.awt.Color(126, 129, 161));
        jButtonImportNodes.setForeground(new java.awt.Color(51, 51, 51));
        jButtonImportNodes.setText("Import Nodes");
        jButtonImportNodes.setBorderPainted(false);
        jButtonImportNodes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImportNodesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 3, 98, 0);
        jPanelNodeConfigurationsScreen.add(jButtonImportNodes, gridBagConstraints);

        jButtonSave.setBackground(new java.awt.Color(126, 129, 161));
        jButtonSave.setForeground(new java.awt.Color(51, 51, 51));
        jButtonSave.setText("Save Node Edition");
        jButtonSave.setBorderPainted(false);
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 51;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.gridwidth = 106;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 89, 0, 71);
        jPanelNodeConfigurationsScreen.add(jButtonSave, gridBagConstraints);

        jLabelTitle2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelTitle2.setForeground(new java.awt.Color(204, 204, 255));
        jLabelTitle2.setText("Edit a node of the network");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 34, 0, 0);
        jPanelNodeConfigurationsScreen.add(jLabelTitle2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 26;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 104;
        gridBagConstraints.ipadx = 248;
        gridBagConstraints.ipady = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 10, 0, 0);
        jPanelNodeConfigurationsScreen.add(jSeparator1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 21;
        gridBagConstraints.gridwidth = 157;
        gridBagConstraints.ipadx = 544;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 34, 0, 71);
        jPanelNodeConfigurationsScreen.add(jSeparator2, gridBagConstraints);

        jLabelName.setBackground(new java.awt.Color(204, 204, 255));
        jLabelName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelName.setForeground(new java.awt.Color(204, 204, 255));
        jLabelName.setText("Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 15;
        gridBagConstraints.ipadx = 184;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 34, 0, 0);
        jPanelNodeConfigurationsScreen.add(jLabelName, gridBagConstraints);

        jTextFieldName.setBackground(new java.awt.Color(69, 71, 95));
        jTextFieldName.setForeground(new java.awt.Color(255, 255, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 15;
        gridBagConstraints.ipadx = 156;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 34, 0, 0);
        jPanelNodeConfigurationsScreen.add(jTextFieldName, gridBagConstraints);

        jLabelStatus.setBackground(new java.awt.Color(204, 204, 255));
        jLabelStatus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelStatus.setForeground(new java.awt.Color(204, 204, 255));
        jLabelStatus.setText("Initial status");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 15;
        gridBagConstraints.ipadx = 146;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 34, 0, 0);
        jPanelNodeConfigurationsScreen.add(jLabelStatus, gridBagConstraints);

        jTextFieldStatus.setBackground(new java.awt.Color(69, 71, 95));
        jTextFieldStatus.setForeground(new java.awt.Color(255, 255, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 15;
        gridBagConstraints.ipadx = 156;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 34, 0, 0);
        jPanelNodeConfigurationsScreen.add(jTextFieldStatus, gridBagConstraints);

        jLabelRestingStatus.setBackground(new java.awt.Color(204, 204, 255));
        jLabelRestingStatus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelRestingStatus.setForeground(new java.awt.Color(204, 204, 255));
        jLabelRestingStatus.setText("Resting status");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 15;
        gridBagConstraints.ipadx = 134;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 34, 0, 0);
        jPanelNodeConfigurationsScreen.add(jLabelRestingStatus, gridBagConstraints);

        jTextFieldRestingStatus.setBackground(new java.awt.Color(69, 71, 95));
        jTextFieldRestingStatus.setForeground(new java.awt.Color(255, 255, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 15;
        gridBagConstraints.ipadx = 156;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 34, 0, 0);
        jPanelNodeConfigurationsScreen.add(jTextFieldRestingStatus, gridBagConstraints);

        jLabelModifications.setBackground(new java.awt.Color(204, 204, 255));
        jLabelModifications.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelModifications.setForeground(new java.awt.Color(204, 204, 255));
        jLabelModifications.setText("Node modifications");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 15;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 102;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 34, 0, 0);
        jPanelNodeConfigurationsScreen.add(jLabelModifications, gridBagConstraints);

        jComboBoxModifications.setBackground(new java.awt.Color(69, 71, 95));
        jComboBoxModifications.setForeground(new java.awt.Color(255, 255, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 15;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.ipadx = 148;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 34, 0, 0);
        jPanelNodeConfigurationsScreen.add(jComboBoxModifications, gridBagConstraints);

        jButtonEditMod.setBackground(new java.awt.Color(126, 129, 161));
        jButtonEditMod.setForeground(new java.awt.Color(51, 51, 51));
        jButtonEditMod.setText("Edit Mod");
        jButtonEditMod.setBorderPainted(false);
        jButtonEditMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditModActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.ipadx = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 0, 0);
        jPanelNodeConfigurationsScreen.add(jButtonEditMod, gridBagConstraints);

        jButtonAddMod.setBackground(new java.awt.Color(126, 129, 161));
        jButtonAddMod.setForeground(new java.awt.Color(51, 51, 51));
        jButtonAddMod.setText("Add Mod");
        jButtonAddMod.setBorderPainted(false);
        jButtonAddMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddModActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 34, 0, 0);
        jPanelNodeConfigurationsScreen.add(jButtonAddMod, gridBagConstraints);

        jLabelType.setBackground(new java.awt.Color(204, 204, 255));
        jLabelType.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelType.setForeground(new java.awt.Color(204, 204, 255));
        jLabelType.setText("Node Type");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 26;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 78;
        gridBagConstraints.ipadx = 130;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 40, 0, 0);
        jPanelNodeConfigurationsScreen.add(jLabelType, gridBagConstraints);

        jLabelIncome.setBackground(new java.awt.Color(204, 204, 255));
        jLabelIncome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelIncome.setForeground(new java.awt.Color(204, 204, 255));
        jLabelIncome.setText("Metabolic income");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 26;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 131;
        gridBagConstraints.ipadx = 112;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 40, 0, 71);
        jPanelNodeConfigurationsScreen.add(jLabelIncome, gridBagConstraints);

        jTextFieldIncome.setBackground(new java.awt.Color(69, 71, 95));
        jTextFieldIncome.setForeground(new java.awt.Color(255, 255, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 26;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 131;
        gridBagConstraints.ipadx = 156;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 40, 0, 71);
        jPanelNodeConfigurationsScreen.add(jTextFieldIncome, gridBagConstraints);

        jLabelMinValue.setBackground(new java.awt.Color(204, 204, 255));
        jLabelMinValue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelMinValue.setForeground(new java.awt.Color(204, 204, 255));
        jLabelMinValue.setText("Metabolic min. value");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 26;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 131;
        gridBagConstraints.ipadx = 94;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 40, 0, 71);
        jPanelNodeConfigurationsScreen.add(jLabelMinValue, gridBagConstraints);

        jTextFieldMinValue.setBackground(new java.awt.Color(69, 71, 95));
        jTextFieldMinValue.setForeground(new java.awt.Color(255, 255, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 26;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 131;
        gridBagConstraints.ipadx = 156;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 40, 0, 71);
        jPanelNodeConfigurationsScreen.add(jTextFieldMinValue, gridBagConstraints);

        jLabelMaxValue.setBackground(new java.awt.Color(204, 204, 255));
        jLabelMaxValue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelMaxValue.setForeground(new java.awt.Color(204, 204, 255));
        jLabelMaxValue.setText("Metabolic max. value");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 26;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 131;
        gridBagConstraints.ipadx = 92;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 40, 0, 71);
        jPanelNodeConfigurationsScreen.add(jLabelMaxValue, gridBagConstraints);

        jTextFieldMaxValue.setBackground(new java.awt.Color(69, 71, 95));
        jTextFieldMaxValue.setForeground(new java.awt.Color(255, 255, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 26;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 131;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 156;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 40, 0, 71);
        jPanelNodeConfigurationsScreen.add(jTextFieldMaxValue, gridBagConstraints);

        jButtonKnockout.setBackground(new java.awt.Color(126, 129, 161));
        jButtonKnockout.setForeground(new java.awt.Color(51, 51, 51));
        jButtonKnockout.setText("Create a knockout");
        jButtonKnockout.setBorderPainted(false);
        jButtonKnockout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKnockoutActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 51;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 106;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 76, 0, 71);
        jPanelNodeConfigurationsScreen.add(jButtonKnockout, gridBagConstraints);

        jButtonAddNode.setBackground(new java.awt.Color(126, 129, 161));
        jButtonAddNode.setForeground(new java.awt.Color(51, 51, 51));
        jButtonAddNode.setText("Create Node");
        jButtonAddNode.setBorderPainted(false);
        jButtonAddNode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddNodeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 51;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 18, 98, 0);
        jPanelNodeConfigurationsScreen.add(jButtonAddNode, gridBagConstraints);

        jTextFieldType.setBackground(new java.awt.Color(69, 71, 95));
        jTextFieldType.setForeground(new java.awt.Color(255, 255, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 26;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 131;
        gridBagConstraints.ipadx = 156;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 40, 0, 71);
        jPanelNodeConfigurationsScreen.add(jTextFieldType, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelNodeConfigurationsScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelNodeConfigurationsScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFilterActionPerformed
        listNodesList.removeAll();
        displayedNodes = nodeFilter.filterNodes(listNodesList, nodeList, jTextFieldFilter.getText());
    }//GEN-LAST:event_jButtonFilterActionPerformed

    private void listNodesListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listNodesListMouseClicked
        // Ensures the item will only be accessed on the second click
        if (evt.getClickCount() == 2) {
            int selectedIndex = listNodesList.getSelectedIndex();
            selectedNode = displayedNodes.get(selectedIndex);
            boolean metabolite = false;
            //
            jTextFieldName.setText(selectedNode.getName());
            jTextFieldStatus.setText(String.valueOf(selectedNode.getStatus()));
            jTextFieldRestingStatus.setText(String.valueOf(selectedNode.getRestingStatus()));
            // Checks if the node has modifications and, if so, populates the ComboBox
            jComboBoxModifications.removeAllItems();
            if (!selectedNode.getNodeModifications().isEmpty()) {
                for (int i = 0; i < selectedNode.getNodeModifications().size(); i++) {
                    jComboBoxModifications.addItem(selectedNode.getNodeModifications().get(i).getName());
                }
            } else {
                jComboBoxModifications.addItem("<none>");
            }
            // Set node type
            switch (selectedNode.getType()) {
                case TYPE_PROTEINGENE:
                    jTextFieldType.setText("Protein/Gene");
                    break;
                case TYPE_METABOLITE:
                    jTextFieldType.setText("Metabolite");
                    break;
                case TYPE_OTHER:
                    jTextFieldType.setText("Other");
                    break;
                case TYPE_MIRNA:
                    jTextFieldType.setText("miRNA");
                    ;
                    break;
                case TYPE_DRUG:
                    jTextFieldType.setText("Drug");
                    break;
                default:
                    throw new AssertionError();
            }
            // If the node is a metabolite, populate specific fields for metabolites. If not, block these fields.
            if (selectedNode.getType() == 2) {
                jTextFieldIncome.setText(String.valueOf(((Metabolite) selectedNode).getIncome()));
                jTextFieldMinValue.setText(String.valueOf(((Metabolite) selectedNode).getMinValue()));
                jTextFieldMaxValue.setText(String.valueOf(((Metabolite) selectedNode).getMaxValue()));
                metabolite = true;
            }

            jTextFieldIncome.setEditable(metabolite);
            jTextFieldMinValue.setEditable(metabolite);
            jTextFieldMaxValue.setEditable(metabolite);
            jTextFieldRestingStatus.setEditable(!metabolite);
            setFieldColor(metabolite);
        }
    }//GEN-LAST:event_listNodesListMouseClicked

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        int dialogResult = JOptionPane.showConfirmDialog(null, "This action will restore the nodes, including their rules, to those provided by default. Would you like to proceed?", "Warning", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
            configurations.networkSourceInputType = "default";
            nodeList = networkFactory.createNetwork(configurations).getDefaultNodes();
            setComponents();
        }
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonExportNodesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExportNodesActionPerformed
        int dialogResult = JOptionPane.showConfirmDialog(null, "This action will save any changes made to the nodes. Would you like to proceed?", "Warning", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
            int returnVal = fileChooser.showOpenDialog(this);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                File file = fileChooser.getSelectedFile();
                try {
                    // Export node settings
                    XMLNetworkWriter.exportNodeList(file.getAbsolutePath(), nodeList);
                    // Concurrently saves node settings to temporary file
                    XMLNetworkWriter.exportNodeList(configurations.networkSourceFileName, nodeList);
                    // Ensures that the system takes into account user-placed node configurations
                    configurations.networkSourceInputType = "xml";
                    JOptionPane.showMessageDialog(this, "Export completed successfully.", "Successful Import", JOptionPane.INFORMATION_MESSAGE);
                } catch (ParserConfigurationException | IOException | SAXException | TransformerException ex) {
                    java.util.logging.Logger.getLogger(NodeConfigurations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
            } else {
                System.out.println("File access cancelled by user.");
            }
        }
    }//GEN-LAST:event_jButtonExportNodesActionPerformed

    private void jButtonImportNodesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImportNodesActionPerformed
        int dialogResult = JOptionPane.showConfirmDialog(null, "This action will replace the current network, including its rules, with the chosen network. Would you like to proceed?", "Warning", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setDialogType(javax.swing.JFileChooser.OPEN_DIALOG);
            int returnVal = fileChooser.showOpenDialog(this);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                try {
                    File file = fileChooser.getSelectedFile();
                    // Replaces the list of current nodes with those submitted by the user.
                    nodeList = XMLNetworkReader.importNodeList(file);
                    // Simultaneously replaces the nodes' local file with those submitted by the user.
                    XMLNetworkWriter.exportNodeList(configurations.networkSourceFileName, nodeList);
                    configurations.networkSourceInputType = "xml";
                    setComponents();
                    JOptionPane.showMessageDialog(this, "File imported successfully.", "Successful Import", JOptionPane.INFORMATION_MESSAGE);
                } catch (ParserConfigurationException | IOException | SAXException | TransformerException ex) {
                    java.util.logging.Logger.getLogger(NodeConfigurations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
            } else {
                System.out.println("File access cancelled by user.");
            }
        }
    }//GEN-LAST:event_jButtonImportNodesActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        int dialogResult = JOptionPane.showConfirmDialog(null, "This action will save any changes made to the nodes. Would you like to proceed?", "Warning", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
            // Checks if a node has been selected by the user.
            if (jTextFieldName.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "[ERROR] No nodes were selected.", "Error - Empty Node", JOptionPane.ERROR_MESSAGE);
                return;
            }
            selectedNode.setStatus(Double.valueOf(jTextFieldStatus.getText()));
            selectedNode.setRestingStatus(Double.valueOf(jTextFieldRestingStatus.getText()));
            selectedNode.setStatus(Double.valueOf(jTextFieldStatus.getText()));
            if (selectedNode.getType() == 2) {
                ((Metabolite) selectedNode).setIncome(Double.valueOf(jTextFieldIncome.getText()));
                ((Metabolite) selectedNode).setMinValue(Double.valueOf(jTextFieldMinValue.getText()));
                ((Metabolite) selectedNode).setMaxValue(Double.valueOf(jTextFieldMaxValue.getText()));
            }
            // Ensures that the network used in the execution contains the changes made by the user.
            configurations.networkSourceInputType = "xml";
        }
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonEditModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditModActionPerformed
        // Checks if a node has been selected by the user.
        if (jTextFieldName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "[ERROR] No nodes were selected.", "Error - Empty Node", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Checks if the node has any modifications to be edited.
        if (jComboBoxModifications.getItemAt(0).equals("<none>")) {
            JOptionPane.showMessageDialog(this, "[ERROR] This node has no modifications available for editing.", "Error - Empty Node", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int modificationIndex = jComboBoxModifications.getSelectedIndex();
        EditModification frame = new EditModification(configurations, nodeList, selectedNode, modificationIndex);
        frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        frame.setVisible(true);
    }//GEN-LAST:event_jButtonEditModActionPerformed

    private void jButtonAddModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddModActionPerformed
        // Checks if a node has been selected by the user.
        if (jTextFieldName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "[ERROR] No nodes were selected.", "Error - Empty Node", JOptionPane.ERROR_MESSAGE);
            return;
        }
        CreateModification frame = new CreateModification(configurations, selectedNode);
        frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        frame.setVisible(true);
    }//GEN-LAST:event_jButtonAddModActionPerformed

    private void jButtonKnockoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKnockoutActionPerformed
        CreateKnockout frame = new CreateKnockout(configurations, nodeList);
        frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        frame.setVisible(true);
    }//GEN-LAST:event_jButtonKnockoutActionPerformed

    private void jButtonAddNodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddNodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddNodeActionPerformed

    public void setFieldColor(boolean metabolic) {
        if (metabolic) {
            jTextFieldIncome.setBackground(colorEnabled);
            jTextFieldMinValue.setBackground(colorEnabled);
            jTextFieldMaxValue.setBackground(colorEnabled);
            jTextFieldRestingStatus.setBackground(colorBlock);

        } else {
            jTextFieldIncome.setBackground(colorBlock);
            jTextFieldMinValue.setBackground(colorBlock);
            jTextFieldMaxValue.setBackground(colorBlock);
            jTextFieldRestingStatus.setBackground(colorEnabled);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddMod;
    private javax.swing.JButton jButtonAddNode;
    private javax.swing.JButton jButtonEditMod;
    private javax.swing.JButton jButtonExportNodes;
    private javax.swing.JButton jButtonFilter;
    private javax.swing.JButton jButtonImportNodes;
    private javax.swing.JButton jButtonKnockout;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JComboBox<String> jComboBoxModifications;
    private javax.swing.JLabel jLabelFilter;
    private javax.swing.JLabel jLabelIncome;
    private javax.swing.JLabel jLabelMaxValue;
    private javax.swing.JLabel jLabelMinValue;
    private javax.swing.JLabel jLabelModifications;
    private javax.swing.JLabel jLabelNCFilter2;
    private javax.swing.JLabel jLabelNCFilter5;
    private javax.swing.JLabel jLabelNCNodesList;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelRestingStatus;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelSubtitle;
    private javax.swing.JLabel jLabelTitle1;
    private javax.swing.JLabel jLabelTitle2;
    private javax.swing.JLabel jLabelType;
    private javax.swing.JPanel jPanelNodeConfigurationsScreen;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextFieldFilter;
    private javax.swing.JTextField jTextFieldIncome;
    private javax.swing.JTextField jTextFieldMaxValue;
    private javax.swing.JTextField jTextFieldMinValue;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldRestingStatus;
    private javax.swing.JTextField jTextFieldStatus;
    private javax.swing.JTextField jTextFieldType;
    private java.awt.List listNodesList;
    // End of variables declaration//GEN-END:variables
}
