/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.pseudocell.gui.cards;

import java.awt.CardLayout;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.util.List;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import org.pseudocell.core.Network;
import org.pseudocell.core.NetworkFactory;
import org.pseudocell.core.nodes.Node;
import org.pseudocell.core.rules.Rule;
import org.pseudocell.config.Config;
import org.pseudocell.gui.components.RuleTree;
import org.pseudocell.gui.tests.DynamicTreeDemo;
import org.pseudocell.gui.utils.NodeFilter;
import org.pseudocell.gui.utils.RuleSummary;

/**
 *
 * @author ViníciusPierdoná
 */
public class RuleConfigurations extends javax.swing.JPanel {
    
    Config configurations;
    List<Node> nodeList, displayedNodes;
    NodeFilter nodeFilter;
    Node selectedNode;
    RuleSummary ruleSummary;
    
    protected DefaultMutableTreeNode rootNode;
    protected DefaultTreeModel treeModel;

    /**
     * Creates new form RuleConfigurations
     */
    public RuleConfigurations(Config configurations, List<Node> nodeList) {
        initComponents();

        this.configurations = configurations;
        this.nodeList = nodeList;
        this.nodeFilter = new NodeFilter();
        this.ruleSummary = new RuleSummary();

        // Create a listener to control the methods needed when shown or hidden the card
        addComponentListener(new ComponentAdapter() {
            @Override
            public void componentHidden(ComponentEvent evt) {
                hidden();
            }

            @Override
            public void componentShown(ComponentEvent evt) {
                shown();
            }
        });
    }

    public void hidden() {

    }

    public void shown() {
        setComponents();
    }

    public void setComponents() {
        displayedNodes = nodeFilter.filterNodes(listNodeList, nodeList, null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanelRuleConfigurationScreen = new javax.swing.JPanel();
        jLabelNPTitle2 = new javax.swing.JLabel();
        jLabelNPSubtitle2 = new javax.swing.JLabel();
        jLabelFilter = new javax.swing.JLabel();
        jTextFieldFilter = new javax.swing.JTextField();
        jButtonFilter = new javax.swing.JButton();
        jLabelNodeList = new javax.swing.JLabel();
        listNodeList = new java.awt.List();
        jLabelRuleList = new javax.swing.JLabel();
        listRuleList = new java.awt.List();
        jSeparator1 = new javax.swing.JSeparator();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setMaximumSize(new java.awt.Dimension(650, 720));
        setPreferredSize(new java.awt.Dimension(650, 720));
        setLayout(new java.awt.GridBagLayout());

        jPanelRuleConfigurationScreen.setBackground(new java.awt.Color(56, 58, 77));
        jPanelRuleConfigurationScreen.setMaximumSize(new java.awt.Dimension(650, 720));
        jPanelRuleConfigurationScreen.setPreferredSize(new java.awt.Dimension(650, 720));

        jLabelNPTitle2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelNPTitle2.setForeground(new java.awt.Color(204, 204, 255));
        jLabelNPTitle2.setText("Edit Network Rules");

        jLabelNPSubtitle2.setBackground(new java.awt.Color(204, 204, 255));
        jLabelNPSubtitle2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNPSubtitle2.setForeground(new java.awt.Color(204, 204, 255));
        jLabelNPSubtitle2.setText("Edit the logic rules that determine the state of nodes.");

        jLabelFilter.setBackground(new java.awt.Color(204, 204, 255));
        jLabelFilter.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelFilter.setForeground(new java.awt.Color(204, 204, 255));
        jLabelFilter.setText("Filter");

        jTextFieldFilter.setBackground(new java.awt.Color(69, 71, 95));
        jTextFieldFilter.setForeground(new java.awt.Color(255, 255, 255));

        jButtonFilter.setBackground(new java.awt.Color(126, 129, 161));
        jButtonFilter.setForeground(new java.awt.Color(51, 51, 51));
        jButtonFilter.setText("Filter");
        jButtonFilter.setBorderPainted(false);
        jButtonFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFilterActionPerformed(evt);
            }
        });

        jLabelNodeList.setBackground(new java.awt.Color(204, 204, 255));
        jLabelNodeList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNodeList.setForeground(new java.awt.Color(204, 204, 255));
        jLabelNodeList.setText("Nodes List");

        listNodeList.setBackground(new java.awt.Color(69, 71, 95));
        listNodeList.setForeground(new java.awt.Color(255, 255, 255));
        listNodeList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listNodeListMouseClicked(evt);
            }
        });

        jLabelRuleList.setBackground(new java.awt.Color(204, 204, 255));
        jLabelRuleList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelRuleList.setForeground(new java.awt.Color(204, 204, 255));
        jLabelRuleList.setText("Rule List");

        listRuleList.setBackground(new java.awt.Color(69, 71, 95));
        listRuleList.setForeground(new java.awt.Color(255, 255, 255));
        listRuleList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listRuleListMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelRuleConfigurationScreenLayout = new javax.swing.GroupLayout(jPanelRuleConfigurationScreen);
        jPanelRuleConfigurationScreen.setLayout(jPanelRuleConfigurationScreenLayout);
        jPanelRuleConfigurationScreenLayout.setHorizontalGroup(
            jPanelRuleConfigurationScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRuleConfigurationScreenLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanelRuleConfigurationScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRuleConfigurationScreenLayout.createSequentialGroup()
                        .addGroup(jPanelRuleConfigurationScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelRuleConfigurationScreenLayout.createSequentialGroup()
                                .addGroup(jPanelRuleConfigurationScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanelRuleConfigurationScreenLayout.createSequentialGroup()
                                        .addComponent(jTextFieldFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonFilter))
                                    .addComponent(jLabelNodeList)
                                    .addComponent(listNodeList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(56, 56, 56)
                                .addGroup(jPanelRuleConfigurationScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelRuleConfigurationScreenLayout.createSequentialGroup()
                                        .addComponent(jLabelRuleList)
                                        .addGap(0, 269, Short.MAX_VALUE))
                                    .addComponent(listRuleList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jSeparator1))
                        .addGap(35, 35, 35))
                    .addGroup(jPanelRuleConfigurationScreenLayout.createSequentialGroup()
                        .addGroup(jPanelRuleConfigurationScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNPTitle2)
                            .addComponent(jLabelNPSubtitle2)
                            .addComponent(jLabelFilter))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelRuleConfigurationScreenLayout.setVerticalGroup(
            jPanelRuleConfigurationScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRuleConfigurationScreenLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabelNPTitle2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNPSubtitle2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelRuleConfigurationScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFilter)
                    .addComponent(jLabelRuleList))
                .addGroup(jPanelRuleConfigurationScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelRuleConfigurationScreenLayout.createSequentialGroup()
                        .addGroup(jPanelRuleConfigurationScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonFilter))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelNodeList)
                        .addGap(2, 2, 2)
                        .addComponent(listNodeList, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(listRuleList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(364, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 269;
        gridBagConstraints.ipady = 358;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(jPanelRuleConfigurationScreen, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void listRuleListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listRuleListMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_listRuleListMouseClicked

    private void listNodeListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listNodeListMouseClicked
        // Ensures the item will only be accessed on the second click
        if (evt.getClickCount() == 2) {
            int nodeIndex = listNodeList.getSelectedIndex();
            selectedNode = displayedNodes.get(nodeIndex);
            listRuleList.removeAll();
            List<String> ruleList = ruleSummary.listRules(selectedNode);
            for (String ruleString : ruleList) {
                listRuleList.add(ruleString);
            }
        }
    }//GEN-LAST:event_listNodeListMouseClicked

    private void jButtonFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFilterActionPerformed
        listNodeList.removeAll();
        displayedNodes = nodeFilter.filterNodes(listNodeList, nodeList, jTextFieldFilter.getText());
    }//GEN-LAST:event_jButtonFilterActionPerformed
    
    public void populateTree(JTree treePanel) {
        NetworkFactory networkFactory = new NetworkFactory();
        Network network = networkFactory.createNetwork(new Config());
        Rule rule = network.getDefaultNodes().get(3).getRules().get(0);
        String ruleString[] = rule.getRuleString().split("(?<=[()&|])|(?=[()&|])");
        DefaultMutableTreeNode currentNode = treePanel.getRootPane();
        DefaultMutableTreeNode fatherNode = treePanel.rootNode;
        int bracketNumber = 1;
        String ruleFragment;
        // Cycles through all elements of the rule
        for (int i = 0; i < ruleString.length; i++) {
            ruleFragment = ruleString[i];
            
            // Controls bracket concatenation
            if(ruleFragment.equals("(")){
                currentNode = treePanel.addObject(fatherNode, "Bracket "+bracketNumber++);
                fatherNode = currentNode;
            } else if (ruleFragment.equals(")")) {
                fatherNode = (DefaultMutableTreeNode) currentNode.getParent().getParent();
            } else            
            // Checks if the current fragment is a relational operation
            if (ruleFragment.startsWith("Node:") || ruleFragment.startsWith("Mod:")) {
                // Checks if the current fragment is the last fragment of the rule
                if (i + 1 < ruleString.length) {
                    // Check for the next logical operator
                    for (int j = i; j < ruleString.length; j++) {                        
                        if (ruleString[j].equals("&") || ruleString[j].equals("|")) {
                            ruleFragment += " " + ruleString[j];
                            break;
                        }
                    }
                }
                currentNode = treePanel.addObject(fatherNode, ruleFragment);
            }            
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFilter;
    private javax.swing.JLabel jLabelFilter;
    private javax.swing.JLabel jLabelNPSubtitle2;
    private javax.swing.JLabel jLabelNPTitle2;
    private javax.swing.JLabel jLabelNodeList;
    private javax.swing.JLabel jLabelRuleList;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanelRuleConfigurationScreen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldFilter;
    private java.awt.List listNodeList;
    private java.awt.List listRuleList;
    // End of variables declaration//GEN-END:variables
}
