/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.pseudocell.gui;

import java.awt.CardLayout;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JPanel;
import org.pseudocell.core.Network;
import org.pseudocell.core.NetworkFactory;
import org.pseudocell.core.PseudocellFactory;
import org.pseudocell.core.nodes.Node;
import org.pseudocell.gui.cards.GeneralConfigurations;
import org.pseudocell.gui.cards.NewProject;
import org.pseudocell.gui.cards.NodeConfigurations;
import org.pseudocell.gui.cards.NodeStimulation;
import org.pseudocell.gui.cards.RuleConfigurations;
import org.pseudocell.config.Config;
import org.pseudocell.config.ConfigNodeStimulation;

/**
 *
 * @author ViniciusPierdona
 */
public class MainOld2 extends javax.swing.JFrame {
    
    private static final String CARD_NEWPROJECT =  "Card jPanelNewProject";
    private static final String CARD_GENERALCONFIGURATIONS = "Card jPanelGeneralConfigurations";    
    private static final String CARD_NODECONFIGURATIONS = "Card jPanelNodeConfigurations";
    private static final String CARD_RULECONFIGURATIONS = "Card jPanelRuleConfigurations";
    private static final String CARD_NODESTIMULATION = "Card jPanelNodeStimulation";
    private List<JPanel> menu;
    String selectedScreen;
    CardLayout cardLayout;
    
    private Config configurations; 
    private ConfigNodeStimulation configNodeStimulation;
    private NetworkFactory networkFactory;
    private PseudocellFactory pseudocellFactory;
    private Network network;
    private List<Node> nodeList;

    public MainOld2() {
        initComponents();
        
        configurations = new Config();
        configNodeStimulation = new ConfigNodeStimulation();
        networkFactory = new NetworkFactory();
        pseudocellFactory = new PseudocellFactory();
        network = networkFactory.createNetwork(configurations);
        nodeList = network.getDefaultNodes();

        // Create List with menu jPanel
        menu = new ArrayList<>();
        menu.add(jPanelNewProject);
        menu.add(jPanelSaveProject);
        menu.add(jPanelGeneralConfigurations);
        menu.add(jPanelNodeConfigurations);
        menu.add(jPanelEditNetwork);
        menu.add(jPanelNodeStimulation);
        // Initialize the Main Screen (New Project)
        cardLayout = (CardLayout) (jPanelMainScreen.getLayout());
        selectedScreen = "jPanelNewProject";
        setCards();
    }
    
    private void setCards(){
        NewProject newProjectPanel = new NewProject(configurations, configNodeStimulation, nodeList);
        jPanelMainScreen.add(newProjectPanel, CARD_NEWPROJECT);
        GeneralConfigurations generalConfigurationsPanel = new GeneralConfigurations(configurations);
        jPanelMainScreen.add(generalConfigurationsPanel, CARD_GENERALCONFIGURATIONS);
        NodeConfigurations nodeConfigurationsPanel = new NodeConfigurations(configurations, nodeList);
        jPanelMainScreen.add(nodeConfigurationsPanel, CARD_NODECONFIGURATIONS);
        RuleConfigurations ruleCOnfigurationsPanel = new RuleConfigurations(configurations, nodeList);
        jPanelMainScreen.add(ruleCOnfigurationsPanel, CARD_RULECONFIGURATIONS);
        NodeStimulation nodeStimulationPanel = new NodeStimulation();
        jPanelMainScreen.add(nodeStimulationPanel, CARD_NODESTIMULATION);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanelMenu = new javax.swing.JPanel();
        jPanelNewProject = new javax.swing.JPanel();
        jLabelNewProject = new javax.swing.JLabel();
        jPanelSaveProject = new javax.swing.JPanel();
        jLabelSaveProject = new javax.swing.JLabel();
        jPanelGeneralConfigurations = new javax.swing.JPanel();
        jLabelLoadConfigurations1 = new javax.swing.JLabel();
        jPanelNodeConfigurations = new javax.swing.JPanel();
        jLabelNodeConfigurations = new javax.swing.JLabel();
        jPanelEditNetwork = new javax.swing.JPanel();
        jLabelNodeConfigurations1 = new javax.swing.JLabel();
        jPanelNodeStimulation = new javax.swing.JPanel();
        jLabelNodeConfigurations3 = new javax.swing.JLabel();
        jPanelMainScreen = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(866, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(866, 720));

        jSplitPane1.setDividerSize(0);

        jPanelMenu.setBackground(new java.awt.Color(39, 40, 55));
        jPanelMenu.setMaximumSize(new java.awt.Dimension(216, 687));

        jPanelNewProject.setBackground(new java.awt.Color(101, 126, 137));
        jPanelNewProject.setName("jPanelNewProject"); // NOI18N
        jPanelNewProject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelNewProjectMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelNewProjectMouseEntered(evt);
            }
        });

        jLabelNewProject.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelNewProject.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNewProject.setText("New Project");

        javax.swing.GroupLayout jPanelNewProjectLayout = new javax.swing.GroupLayout(jPanelNewProject);
        jPanelNewProject.setLayout(jPanelNewProjectLayout);
        jPanelNewProjectLayout.setHorizontalGroup(
            jPanelNewProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNewProjectLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabelNewProject)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelNewProjectLayout.setVerticalGroup(
            jPanelNewProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNewProjectLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabelNewProject)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanelSaveProject.setBackground(new java.awt.Color(77, 92, 99));
        jPanelSaveProject.setName("jPanelSaveProject"); // NOI18N
        jPanelSaveProject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelSaveProjectMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelSaveProjectMouseEntered(evt);
            }
        });

        jLabelSaveProject.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelSaveProject.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSaveProject.setText("Save Project");

        javax.swing.GroupLayout jPanelSaveProjectLayout = new javax.swing.GroupLayout(jPanelSaveProject);
        jPanelSaveProject.setLayout(jPanelSaveProjectLayout);
        jPanelSaveProjectLayout.setHorizontalGroup(
            jPanelSaveProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSaveProjectLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabelSaveProject)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSaveProjectLayout.setVerticalGroup(
            jPanelSaveProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSaveProjectLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabelSaveProject)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanelGeneralConfigurations.setBackground(new java.awt.Color(77, 92, 99));
        jPanelGeneralConfigurations.setName("jPanelGeneralConfigurations"); // NOI18N
        jPanelGeneralConfigurations.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelGeneralConfigurationsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelGeneralConfigurationsMouseEntered(evt);
            }
        });

        jLabelLoadConfigurations1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelLoadConfigurations1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLoadConfigurations1.setText("General Configurations");

        javax.swing.GroupLayout jPanelGeneralConfigurationsLayout = new javax.swing.GroupLayout(jPanelGeneralConfigurations);
        jPanelGeneralConfigurations.setLayout(jPanelGeneralConfigurationsLayout);
        jPanelGeneralConfigurationsLayout.setHorizontalGroup(
            jPanelGeneralConfigurationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeneralConfigurationsLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabelLoadConfigurations1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelGeneralConfigurationsLayout.setVerticalGroup(
            jPanelGeneralConfigurationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeneralConfigurationsLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabelLoadConfigurations1)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanelNodeConfigurations.setBackground(new java.awt.Color(77, 92, 99));
        jPanelNodeConfigurations.setName("jPanelNodeConfigurations"); // NOI18N
        jPanelNodeConfigurations.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelNodeConfigurationssMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelNodeConfigurationssMouseEntered(evt);
            }
        });

        jLabelNodeConfigurations.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelNodeConfigurations.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNodeConfigurations.setText("Node Configurations");

        javax.swing.GroupLayout jPanelNodeConfigurationsLayout = new javax.swing.GroupLayout(jPanelNodeConfigurations);
        jPanelNodeConfigurations.setLayout(jPanelNodeConfigurationsLayout);
        jPanelNodeConfigurationsLayout.setHorizontalGroup(
            jPanelNodeConfigurationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNodeConfigurationsLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabelNodeConfigurations)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelNodeConfigurationsLayout.setVerticalGroup(
            jPanelNodeConfigurationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNodeConfigurationsLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabelNodeConfigurations)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanelEditNetwork.setBackground(new java.awt.Color(77, 92, 99));
        jPanelEditNetwork.setName("jPanelEditNetwork"); // NOI18N
        jPanelEditNetwork.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelEditNetworkMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelEditNetworkMouseEntered(evt);
            }
        });

        jLabelNodeConfigurations1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelNodeConfigurations1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNodeConfigurations1.setText("Edit Network");

        javax.swing.GroupLayout jPanelEditNetworkLayout = new javax.swing.GroupLayout(jPanelEditNetwork);
        jPanelEditNetwork.setLayout(jPanelEditNetworkLayout);
        jPanelEditNetworkLayout.setHorizontalGroup(
            jPanelEditNetworkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditNetworkLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabelNodeConfigurations1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelEditNetworkLayout.setVerticalGroup(
            jPanelEditNetworkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditNetworkLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabelNodeConfigurations1)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanelNodeStimulation.setBackground(new java.awt.Color(77, 92, 99));
        jPanelNodeStimulation.setName("jPanelNodeStimulation"); // NOI18N
        jPanelNodeStimulation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelNodeStimulationMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelNodeStimulationMouseEntered(evt);
            }
        });

        jLabelNodeConfigurations3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelNodeConfigurations3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNodeConfigurations3.setText("Node Stimulation");

        javax.swing.GroupLayout jPanelNodeStimulationLayout = new javax.swing.GroupLayout(jPanelNodeStimulation);
        jPanelNodeStimulation.setLayout(jPanelNodeStimulationLayout);
        jPanelNodeStimulationLayout.setHorizontalGroup(
            jPanelNodeStimulationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNodeStimulationLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabelNodeConfigurations3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelNodeStimulationLayout.setVerticalGroup(
            jPanelNodeStimulationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNodeStimulationLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabelNodeConfigurations3)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelNewProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelSaveProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelGeneralConfigurations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelNodeConfigurations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelEditNetwork, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelNodeStimulation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jPanelNewProject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelSaveProject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addComponent(jPanelGeneralConfigurations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelNodeConfigurations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelEditNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelNodeStimulation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanelMenu);

        jPanelMainScreen.setMaximumSize(new java.awt.Dimension(650, 720));
        jPanelMainScreen.setPreferredSize(new java.awt.Dimension(650, 720));
        jPanelMainScreen.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(jPanelMainScreen);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 866, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSplitPane1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 687, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelNewProjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelNewProjectMouseClicked
        cardLayout.show(jPanelMainScreen, CARD_NEWPROJECT);
        selectedScreen = evt.getComponent().getName();
        setMenuColor((JPanel) evt.getComponent(), "mouseClicked");
    }//GEN-LAST:event_jPanelNewProjectMouseClicked

    private void jPanelSaveProjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSaveProjectMouseClicked
        cardLayout.show(jPanelMainScreen, "jPanelSaveConfigurationsScreen");
        selectedScreen = evt.getComponent().getName();
        setMenuColor((JPanel) evt.getComponent(), "mouseClicked");
    }//GEN-LAST:event_jPanelSaveProjectMouseClicked

    private void jPanelGeneralConfigurationsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelGeneralConfigurationsMouseClicked
        cardLayout.show(jPanelMainScreen, CARD_GENERALCONFIGURATIONS);
        selectedScreen = evt.getComponent().getName();
        setMenuColor((JPanel) evt.getComponent(), "mouseClicked");
    }//GEN-LAST:event_jPanelGeneralConfigurationsMouseClicked

    private void jPanelNodeConfigurationssMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelNodeConfigurationssMouseClicked
        cardLayout.show(jPanelMainScreen, CARD_NODECONFIGURATIONS);
        selectedScreen = evt.getComponent().getName();
        setMenuColor((JPanel) evt.getComponent(), "mouseClicked");
    }//GEN-LAST:event_jPanelNodeConfigurationssMouseClicked

     private void jPanelEditNetworkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelEditNetworkMouseClicked
         cardLayout.show(jPanelMainScreen, CARD_RULECONFIGURATIONS);
         selectedScreen = evt.getComponent().getName();
         setMenuColor((JPanel) evt.getComponent(), "mouseClicked");
    }//GEN-LAST:event_jPanelEditNetworkMouseClicked

    private void jPanelNodeStimulationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelNodeStimulationMouseClicked
        cardLayout.show(jPanelMainScreen, CARD_NODESTIMULATION);
        selectedScreen = evt.getComponent().getName();
        setMenuColor((JPanel) evt.getComponent(), "mouseClicked");
    }//GEN-LAST:event_jPanelNodeStimulationMouseClicked

    private void jPanelNewProjectMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelNewProjectMouseEntered
        setMenuColor((JPanel) evt.getComponent(), "mouseEntered");
    }//GEN-LAST:event_jPanelNewProjectMouseEntered

    private void jPanelSaveProjectMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSaveProjectMouseEntered
        setMenuColor((JPanel) evt.getComponent(), "mouseEntered");
    }//GEN-LAST:event_jPanelSaveProjectMouseEntered

    private void jPanelGeneralConfigurationsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelGeneralConfigurationsMouseEntered
        setMenuColor((JPanel) evt.getComponent(), "mouseEntered");
    }//GEN-LAST:event_jPanelGeneralConfigurationsMouseEntered

    private void jPanelNodeConfigurationssMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelNodeConfigurationssMouseEntered
        setMenuColor((JPanel) evt.getComponent(), "mouseEntered");
    }//GEN-LAST:event_jPanelNodeConfigurationssMouseEntered

    private void jPanelEditNetworkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelEditNetworkMouseEntered
        setMenuColor((JPanel) evt.getComponent(), "mouseEntered");
    }//GEN-LAST:event_jPanelEditNetworkMouseEntered

    private void jPanelNodeStimulationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelNodeStimulationMouseEntered
        setMenuColor((JPanel) evt.getComponent(), "mouseEntered");
    }//GEN-LAST:event_jPanelNodeStimulationMouseEntered

    public void setMenuColor(JPanel selectedPanel, String evtType) {
        if (evtType.equals("mouseClicked")) {
            for (JPanel panel : menu) {
                if (selectedPanel.getName().equals(panel.getName())) {
                    panel.setBackground(new Color(101, 126, 137));
                } else {
                    panel.setBackground(new Color(77, 92, 99));
                }
            }
        } else if (evtType.equals("mouseEntered")) {
            for (JPanel panel : menu) {
                if (!panel.getName().equals(selectedScreen)) {
                    if (selectedPanel.getName().equals(panel.getName())) {
                        panel.setBackground(new Color(95, 114, 123));
                    } else {
                        if (!panel.getName().equals(selectedScreen)) {
                            panel.setBackground(new Color(77, 92, 99));
                        }
                    }
                }
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainOld2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainOld2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainOld2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainOld2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainOld2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelLoadConfigurations1;
    private javax.swing.JLabel jLabelNewProject;
    private javax.swing.JLabel jLabelNodeConfigurations;
    private javax.swing.JLabel jLabelNodeConfigurations1;
    private javax.swing.JLabel jLabelNodeConfigurations3;
    private javax.swing.JLabel jLabelSaveProject;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelEditNetwork;
    private javax.swing.JPanel jPanelGeneralConfigurations;
    private javax.swing.JPanel jPanelMainScreen;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelNewProject;
    private javax.swing.JPanel jPanelNodeConfigurations;
    private javax.swing.JPanel jPanelNodeStimulation;
    private javax.swing.JPanel jPanelSaveProject;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
